-- Generated by
--       _______     _             __
--      / _   __|   | |           / /
--     / / | | _  __| |_ __ ___  / /
--    / /  | || |/ _` | '__/ _ \/ /
--   / /   | || | (_| | | |  __/ /
--  /_/    |_||_|\__,_|_|  \____/
--
-- Copyright 2020 Teratide B.V.
-- 
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
-- 
--     http://www.apache.org/licenses/LICENSE-2.0
-- 
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library work;
use work.UtilInt_pkg.all;

entity Kernel is
  generic (
    INDEX_WIDTH : integer := 32;
    TAG_WIDTH   : integer := 1
  );
  port (
    kcd_clk                          : in  std_logic;
    kcd_reset                        : in  std_logic;
    rematch000_in_valid              : in  std_logic;
    rematch000_in_ready              : out std_logic;
    rematch000_in_dvalid             : in  std_logic;
    rematch000_in_last               : in  std_logic;
    rematch000_in_length             : in  std_logic_vector(31 downto 0);
    rematch000_in_count              : in  std_logic_vector(0 downto 0);
    rematch000_in_chars_valid        : in  std_logic;
    rematch000_in_chars_ready        : out std_logic;
    rematch000_in_chars_dvalid       : in  std_logic;
    rematch000_in_chars_last         : in  std_logic;
    rematch000_in_chars              : in  std_logic_vector(31 downto 0);
    rematch000_in_chars_count        : in  std_logic_vector(2 downto 0);
    rematch000_in_unl_valid          : in  std_logic;
    rematch000_in_unl_ready          : out std_logic;
    rematch000_in_unl_tag            : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch000_in_cmd_valid          : out std_logic;
    rematch000_in_cmd_ready          : in  std_logic;
    rematch000_in_cmd_firstIdx       : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch000_in_cmd_lastIdx        : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch000_in_cmd_tag            : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch001_in_valid              : in  std_logic;
    rematch001_in_ready              : out std_logic;
    rematch001_in_dvalid             : in  std_logic;
    rematch001_in_last               : in  std_logic;
    rematch001_in_length             : in  std_logic_vector(31 downto 0);
    rematch001_in_count              : in  std_logic_vector(0 downto 0);
    rematch001_in_chars_valid        : in  std_logic;
    rematch001_in_chars_ready        : out std_logic;
    rematch001_in_chars_dvalid       : in  std_logic;
    rematch001_in_chars_last         : in  std_logic;
    rematch001_in_chars              : in  std_logic_vector(31 downto 0);
    rematch001_in_chars_count        : in  std_logic_vector(2 downto 0);
    rematch001_in_unl_valid          : in  std_logic;
    rematch001_in_unl_ready          : out std_logic;
    rematch001_in_unl_tag            : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch001_in_cmd_valid          : out std_logic;
    rematch001_in_cmd_ready          : in  std_logic;
    rematch001_in_cmd_firstIdx       : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch001_in_cmd_lastIdx        : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch001_in_cmd_tag            : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch002_in_valid              : in  std_logic;
    rematch002_in_ready              : out std_logic;
    rematch002_in_dvalid             : in  std_logic;
    rematch002_in_last               : in  std_logic;
    rematch002_in_length             : in  std_logic_vector(31 downto 0);
    rematch002_in_count              : in  std_logic_vector(0 downto 0);
    rematch002_in_chars_valid        : in  std_logic;
    rematch002_in_chars_ready        : out std_logic;
    rematch002_in_chars_dvalid       : in  std_logic;
    rematch002_in_chars_last         : in  std_logic;
    rematch002_in_chars              : in  std_logic_vector(31 downto 0);
    rematch002_in_chars_count        : in  std_logic_vector(2 downto 0);
    rematch002_in_unl_valid          : in  std_logic;
    rematch002_in_unl_ready          : out std_logic;
    rematch002_in_unl_tag            : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch002_in_cmd_valid          : out std_logic;
    rematch002_in_cmd_ready          : in  std_logic;
    rematch002_in_cmd_firstIdx       : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch002_in_cmd_lastIdx        : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch002_in_cmd_tag            : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch003_in_valid              : in  std_logic;
    rematch003_in_ready              : out std_logic;
    rematch003_in_dvalid             : in  std_logic;
    rematch003_in_last               : in  std_logic;
    rematch003_in_length             : in  std_logic_vector(31 downto 0);
    rematch003_in_count              : in  std_logic_vector(0 downto 0);
    rematch003_in_chars_valid        : in  std_logic;
    rematch003_in_chars_ready        : out std_logic;
    rematch003_in_chars_dvalid       : in  std_logic;
    rematch003_in_chars_last         : in  std_logic;
    rematch003_in_chars              : in  std_logic_vector(31 downto 0);
    rematch003_in_chars_count        : in  std_logic_vector(2 downto 0);
    rematch003_in_unl_valid          : in  std_logic;
    rematch003_in_unl_ready          : out std_logic;
    rematch003_in_unl_tag            : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch003_in_cmd_valid          : out std_logic;
    rematch003_in_cmd_ready          : in  std_logic;
    rematch003_in_cmd_firstIdx       : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch003_in_cmd_lastIdx        : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch003_in_cmd_tag            : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch004_in_valid              : in  std_logic;
    rematch004_in_ready              : out std_logic;
    rematch004_in_dvalid             : in  std_logic;
    rematch004_in_last               : in  std_logic;
    rematch004_in_length             : in  std_logic_vector(31 downto 0);
    rematch004_in_count              : in  std_logic_vector(0 downto 0);
    rematch004_in_chars_valid        : in  std_logic;
    rematch004_in_chars_ready        : out std_logic;
    rematch004_in_chars_dvalid       : in  std_logic;
    rematch004_in_chars_last         : in  std_logic;
    rematch004_in_chars              : in  std_logic_vector(31 downto 0);
    rematch004_in_chars_count        : in  std_logic_vector(2 downto 0);
    rematch004_in_unl_valid          : in  std_logic;
    rematch004_in_unl_ready          : out std_logic;
    rematch004_in_unl_tag            : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch004_in_cmd_valid          : out std_logic;
    rematch004_in_cmd_ready          : in  std_logic;
    rematch004_in_cmd_firstIdx       : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch004_in_cmd_lastIdx        : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch004_in_cmd_tag            : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch005_in_valid              : in  std_logic;
    rematch005_in_ready              : out std_logic;
    rematch005_in_dvalid             : in  std_logic;
    rematch005_in_last               : in  std_logic;
    rematch005_in_length             : in  std_logic_vector(31 downto 0);
    rematch005_in_count              : in  std_logic_vector(0 downto 0);
    rematch005_in_chars_valid        : in  std_logic;
    rematch005_in_chars_ready        : out std_logic;
    rematch005_in_chars_dvalid       : in  std_logic;
    rematch005_in_chars_last         : in  std_logic;
    rematch005_in_chars              : in  std_logic_vector(31 downto 0);
    rematch005_in_chars_count        : in  std_logic_vector(2 downto 0);
    rematch005_in_unl_valid          : in  std_logic;
    rematch005_in_unl_ready          : out std_logic;
    rematch005_in_unl_tag            : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch005_in_cmd_valid          : out std_logic;
    rematch005_in_cmd_ready          : in  std_logic;
    rematch005_in_cmd_firstIdx       : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch005_in_cmd_lastIdx        : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch005_in_cmd_tag            : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch006_in_valid              : in  std_logic;
    rematch006_in_ready              : out std_logic;
    rematch006_in_dvalid             : in  std_logic;
    rematch006_in_last               : in  std_logic;
    rematch006_in_length             : in  std_logic_vector(31 downto 0);
    rematch006_in_count              : in  std_logic_vector(0 downto 0);
    rematch006_in_chars_valid        : in  std_logic;
    rematch006_in_chars_ready        : out std_logic;
    rematch006_in_chars_dvalid       : in  std_logic;
    rematch006_in_chars_last         : in  std_logic;
    rematch006_in_chars              : in  std_logic_vector(31 downto 0);
    rematch006_in_chars_count        : in  std_logic_vector(2 downto 0);
    rematch006_in_unl_valid          : in  std_logic;
    rematch006_in_unl_ready          : out std_logic;
    rematch006_in_unl_tag            : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch006_in_cmd_valid          : out std_logic;
    rematch006_in_cmd_ready          : in  std_logic;
    rematch006_in_cmd_firstIdx       : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch006_in_cmd_lastIdx        : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch006_in_cmd_tag            : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch007_in_valid              : in  std_logic;
    rematch007_in_ready              : out std_logic;
    rematch007_in_dvalid             : in  std_logic;
    rematch007_in_last               : in  std_logic;
    rematch007_in_length             : in  std_logic_vector(31 downto 0);
    rematch007_in_count              : in  std_logic_vector(0 downto 0);
    rematch007_in_chars_valid        : in  std_logic;
    rematch007_in_chars_ready        : out std_logic;
    rematch007_in_chars_dvalid       : in  std_logic;
    rematch007_in_chars_last         : in  std_logic;
    rematch007_in_chars              : in  std_logic_vector(31 downto 0);
    rematch007_in_chars_count        : in  std_logic_vector(2 downto 0);
    rematch007_in_unl_valid          : in  std_logic;
    rematch007_in_unl_ready          : out std_logic;
    rematch007_in_unl_tag            : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch007_in_cmd_valid          : out std_logic;
    rematch007_in_cmd_ready          : in  std_logic;
    rematch007_in_cmd_firstIdx       : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch007_in_cmd_lastIdx        : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch007_in_cmd_tag            : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch008_in_valid              : in  std_logic;
    rematch008_in_ready              : out std_logic;
    rematch008_in_dvalid             : in  std_logic;
    rematch008_in_last               : in  std_logic;
    rematch008_in_length             : in  std_logic_vector(31 downto 0);
    rematch008_in_count              : in  std_logic_vector(0 downto 0);
    rematch008_in_chars_valid        : in  std_logic;
    rematch008_in_chars_ready        : out std_logic;
    rematch008_in_chars_dvalid       : in  std_logic;
    rematch008_in_chars_last         : in  std_logic;
    rematch008_in_chars              : in  std_logic_vector(31 downto 0);
    rematch008_in_chars_count        : in  std_logic_vector(2 downto 0);
    rematch008_in_unl_valid          : in  std_logic;
    rematch008_in_unl_ready          : out std_logic;
    rematch008_in_unl_tag            : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch008_in_cmd_valid          : out std_logic;
    rematch008_in_cmd_ready          : in  std_logic;
    rematch008_in_cmd_firstIdx       : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch008_in_cmd_lastIdx        : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch008_in_cmd_tag            : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch009_in_valid              : in  std_logic;
    rematch009_in_ready              : out std_logic;
    rematch009_in_dvalid             : in  std_logic;
    rematch009_in_last               : in  std_logic;
    rematch009_in_length             : in  std_logic_vector(31 downto 0);
    rematch009_in_count              : in  std_logic_vector(0 downto 0);
    rematch009_in_chars_valid        : in  std_logic;
    rematch009_in_chars_ready        : out std_logic;
    rematch009_in_chars_dvalid       : in  std_logic;
    rematch009_in_chars_last         : in  std_logic;
    rematch009_in_chars              : in  std_logic_vector(31 downto 0);
    rematch009_in_chars_count        : in  std_logic_vector(2 downto 0);
    rematch009_in_unl_valid          : in  std_logic;
    rematch009_in_unl_ready          : out std_logic;
    rematch009_in_unl_tag            : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch009_in_cmd_valid          : out std_logic;
    rematch009_in_cmd_ready          : in  std_logic;
    rematch009_in_cmd_firstIdx       : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch009_in_cmd_lastIdx        : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch009_in_cmd_tag            : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch010_in_valid              : in  std_logic;
    rematch010_in_ready              : out std_logic;
    rematch010_in_dvalid             : in  std_logic;
    rematch010_in_last               : in  std_logic;
    rematch010_in_length             : in  std_logic_vector(31 downto 0);
    rematch010_in_count              : in  std_logic_vector(0 downto 0);
    rematch010_in_chars_valid        : in  std_logic;
    rematch010_in_chars_ready        : out std_logic;
    rematch010_in_chars_dvalid       : in  std_logic;
    rematch010_in_chars_last         : in  std_logic;
    rematch010_in_chars              : in  std_logic_vector(31 downto 0);
    rematch010_in_chars_count        : in  std_logic_vector(2 downto 0);
    rematch010_in_unl_valid          : in  std_logic;
    rematch010_in_unl_ready          : out std_logic;
    rematch010_in_unl_tag            : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch010_in_cmd_valid          : out std_logic;
    rematch010_in_cmd_ready          : in  std_logic;
    rematch010_in_cmd_firstIdx       : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch010_in_cmd_lastIdx        : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch010_in_cmd_tag            : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch011_in_valid              : in  std_logic;
    rematch011_in_ready              : out std_logic;
    rematch011_in_dvalid             : in  std_logic;
    rematch011_in_last               : in  std_logic;
    rematch011_in_length             : in  std_logic_vector(31 downto 0);
    rematch011_in_count              : in  std_logic_vector(0 downto 0);
    rematch011_in_chars_valid        : in  std_logic;
    rematch011_in_chars_ready        : out std_logic;
    rematch011_in_chars_dvalid       : in  std_logic;
    rematch011_in_chars_last         : in  std_logic;
    rematch011_in_chars              : in  std_logic_vector(31 downto 0);
    rematch011_in_chars_count        : in  std_logic_vector(2 downto 0);
    rematch011_in_unl_valid          : in  std_logic;
    rematch011_in_unl_ready          : out std_logic;
    rematch011_in_unl_tag            : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch011_in_cmd_valid          : out std_logic;
    rematch011_in_cmd_ready          : in  std_logic;
    rematch011_in_cmd_firstIdx       : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch011_in_cmd_lastIdx        : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch011_in_cmd_tag            : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch012_in_valid              : in  std_logic;
    rematch012_in_ready              : out std_logic;
    rematch012_in_dvalid             : in  std_logic;
    rematch012_in_last               : in  std_logic;
    rematch012_in_length             : in  std_logic_vector(31 downto 0);
    rematch012_in_count              : in  std_logic_vector(0 downto 0);
    rematch012_in_chars_valid        : in  std_logic;
    rematch012_in_chars_ready        : out std_logic;
    rematch012_in_chars_dvalid       : in  std_logic;
    rematch012_in_chars_last         : in  std_logic;
    rematch012_in_chars              : in  std_logic_vector(31 downto 0);
    rematch012_in_chars_count        : in  std_logic_vector(2 downto 0);
    rematch012_in_unl_valid          : in  std_logic;
    rematch012_in_unl_ready          : out std_logic;
    rematch012_in_unl_tag            : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch012_in_cmd_valid          : out std_logic;
    rematch012_in_cmd_ready          : in  std_logic;
    rematch012_in_cmd_firstIdx       : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch012_in_cmd_lastIdx        : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch012_in_cmd_tag            : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch013_in_valid              : in  std_logic;
    rematch013_in_ready              : out std_logic;
    rematch013_in_dvalid             : in  std_logic;
    rematch013_in_last               : in  std_logic;
    rematch013_in_length             : in  std_logic_vector(31 downto 0);
    rematch013_in_count              : in  std_logic_vector(0 downto 0);
    rematch013_in_chars_valid        : in  std_logic;
    rematch013_in_chars_ready        : out std_logic;
    rematch013_in_chars_dvalid       : in  std_logic;
    rematch013_in_chars_last         : in  std_logic;
    rematch013_in_chars              : in  std_logic_vector(31 downto 0);
    rematch013_in_chars_count        : in  std_logic_vector(2 downto 0);
    rematch013_in_unl_valid          : in  std_logic;
    rematch013_in_unl_ready          : out std_logic;
    rematch013_in_unl_tag            : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch013_in_cmd_valid          : out std_logic;
    rematch013_in_cmd_ready          : in  std_logic;
    rematch013_in_cmd_firstIdx       : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch013_in_cmd_lastIdx        : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch013_in_cmd_tag            : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch014_in_valid              : in  std_logic;
    rematch014_in_ready              : out std_logic;
    rematch014_in_dvalid             : in  std_logic;
    rematch014_in_last               : in  std_logic;
    rematch014_in_length             : in  std_logic_vector(31 downto 0);
    rematch014_in_count              : in  std_logic_vector(0 downto 0);
    rematch014_in_chars_valid        : in  std_logic;
    rematch014_in_chars_ready        : out std_logic;
    rematch014_in_chars_dvalid       : in  std_logic;
    rematch014_in_chars_last         : in  std_logic;
    rematch014_in_chars              : in  std_logic_vector(31 downto 0);
    rematch014_in_chars_count        : in  std_logic_vector(2 downto 0);
    rematch014_in_unl_valid          : in  std_logic;
    rematch014_in_unl_ready          : out std_logic;
    rematch014_in_unl_tag            : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch014_in_cmd_valid          : out std_logic;
    rematch014_in_cmd_ready          : in  std_logic;
    rematch014_in_cmd_firstIdx       : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch014_in_cmd_lastIdx        : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch014_in_cmd_tag            : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch015_in_valid              : in  std_logic;
    rematch015_in_ready              : out std_logic;
    rematch015_in_dvalid             : in  std_logic;
    rematch015_in_last               : in  std_logic;
    rematch015_in_length             : in  std_logic_vector(31 downto 0);
    rematch015_in_count              : in  std_logic_vector(0 downto 0);
    rematch015_in_chars_valid        : in  std_logic;
    rematch015_in_chars_ready        : out std_logic;
    rematch015_in_chars_dvalid       : in  std_logic;
    rematch015_in_chars_last         : in  std_logic;
    rematch015_in_chars              : in  std_logic_vector(31 downto 0);
    rematch015_in_chars_count        : in  std_logic_vector(2 downto 0);
    rematch015_in_unl_valid          : in  std_logic;
    rematch015_in_unl_ready          : out std_logic;
    rematch015_in_unl_tag            : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch015_in_cmd_valid          : out std_logic;
    rematch015_in_cmd_ready          : in  std_logic;
    rematch015_in_cmd_firstIdx       : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch015_in_cmd_lastIdx        : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch015_in_cmd_tag            : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch000_taxi_out_valid        : out std_logic;
    rematch000_taxi_out_ready        : in  std_logic;
    rematch000_taxi_out_dvalid       : out std_logic;
    rematch000_taxi_out_last         : out std_logic;
    rematch000_taxi_out              : out std_logic_vector(31 downto 0);
    rematch000_taxi_out_unl_valid    : in  std_logic;
    rematch000_taxi_out_unl_ready    : out std_logic;
    rematch000_taxi_out_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch000_taxi_out_cmd_valid    : out std_logic;
    rematch000_taxi_out_cmd_ready    : in  std_logic;
    rematch000_taxi_out_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch000_taxi_out_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch000_taxi_out_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch001_taxi_out_valid        : out std_logic;
    rematch001_taxi_out_ready        : in  std_logic;
    rematch001_taxi_out_dvalid       : out std_logic;
    rematch001_taxi_out_last         : out std_logic;
    rematch001_taxi_out              : out std_logic_vector(31 downto 0);
    rematch001_taxi_out_unl_valid    : in  std_logic;
    rematch001_taxi_out_unl_ready    : out std_logic;
    rematch001_taxi_out_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch001_taxi_out_cmd_valid    : out std_logic;
    rematch001_taxi_out_cmd_ready    : in  std_logic;
    rematch001_taxi_out_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch001_taxi_out_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch001_taxi_out_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch002_taxi_out_valid        : out std_logic;
    rematch002_taxi_out_ready        : in  std_logic;
    rematch002_taxi_out_dvalid       : out std_logic;
    rematch002_taxi_out_last         : out std_logic;
    rematch002_taxi_out              : out std_logic_vector(31 downto 0);
    rematch002_taxi_out_unl_valid    : in  std_logic;
    rematch002_taxi_out_unl_ready    : out std_logic;
    rematch002_taxi_out_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch002_taxi_out_cmd_valid    : out std_logic;
    rematch002_taxi_out_cmd_ready    : in  std_logic;
    rematch002_taxi_out_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch002_taxi_out_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch002_taxi_out_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch003_taxi_out_valid        : out std_logic;
    rematch003_taxi_out_ready        : in  std_logic;
    rematch003_taxi_out_dvalid       : out std_logic;
    rematch003_taxi_out_last         : out std_logic;
    rematch003_taxi_out              : out std_logic_vector(31 downto 0);
    rematch003_taxi_out_unl_valid    : in  std_logic;
    rematch003_taxi_out_unl_ready    : out std_logic;
    rematch003_taxi_out_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch003_taxi_out_cmd_valid    : out std_logic;
    rematch003_taxi_out_cmd_ready    : in  std_logic;
    rematch003_taxi_out_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch003_taxi_out_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch003_taxi_out_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch004_taxi_out_valid        : out std_logic;
    rematch004_taxi_out_ready        : in  std_logic;
    rematch004_taxi_out_dvalid       : out std_logic;
    rematch004_taxi_out_last         : out std_logic;
    rematch004_taxi_out              : out std_logic_vector(31 downto 0);
    rematch004_taxi_out_unl_valid    : in  std_logic;
    rematch004_taxi_out_unl_ready    : out std_logic;
    rematch004_taxi_out_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch004_taxi_out_cmd_valid    : out std_logic;
    rematch004_taxi_out_cmd_ready    : in  std_logic;
    rematch004_taxi_out_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch004_taxi_out_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch004_taxi_out_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch005_taxi_out_valid        : out std_logic;
    rematch005_taxi_out_ready        : in  std_logic;
    rematch005_taxi_out_dvalid       : out std_logic;
    rematch005_taxi_out_last         : out std_logic;
    rematch005_taxi_out              : out std_logic_vector(31 downto 0);
    rematch005_taxi_out_unl_valid    : in  std_logic;
    rematch005_taxi_out_unl_ready    : out std_logic;
    rematch005_taxi_out_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch005_taxi_out_cmd_valid    : out std_logic;
    rematch005_taxi_out_cmd_ready    : in  std_logic;
    rematch005_taxi_out_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch005_taxi_out_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch005_taxi_out_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch006_taxi_out_valid        : out std_logic;
    rematch006_taxi_out_ready        : in  std_logic;
    rematch006_taxi_out_dvalid       : out std_logic;
    rematch006_taxi_out_last         : out std_logic;
    rematch006_taxi_out              : out std_logic_vector(31 downto 0);
    rematch006_taxi_out_unl_valid    : in  std_logic;
    rematch006_taxi_out_unl_ready    : out std_logic;
    rematch006_taxi_out_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch006_taxi_out_cmd_valid    : out std_logic;
    rematch006_taxi_out_cmd_ready    : in  std_logic;
    rematch006_taxi_out_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch006_taxi_out_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch006_taxi_out_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch007_taxi_out_valid        : out std_logic;
    rematch007_taxi_out_ready        : in  std_logic;
    rematch007_taxi_out_dvalid       : out std_logic;
    rematch007_taxi_out_last         : out std_logic;
    rematch007_taxi_out              : out std_logic_vector(31 downto 0);
    rematch007_taxi_out_unl_valid    : in  std_logic;
    rematch007_taxi_out_unl_ready    : out std_logic;
    rematch007_taxi_out_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch007_taxi_out_cmd_valid    : out std_logic;
    rematch007_taxi_out_cmd_ready    : in  std_logic;
    rematch007_taxi_out_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch007_taxi_out_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch007_taxi_out_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch008_taxi_out_valid        : out std_logic;
    rematch008_taxi_out_ready        : in  std_logic;
    rematch008_taxi_out_dvalid       : out std_logic;
    rematch008_taxi_out_last         : out std_logic;
    rematch008_taxi_out              : out std_logic_vector(31 downto 0);
    rematch008_taxi_out_unl_valid    : in  std_logic;
    rematch008_taxi_out_unl_ready    : out std_logic;
    rematch008_taxi_out_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch008_taxi_out_cmd_valid    : out std_logic;
    rematch008_taxi_out_cmd_ready    : in  std_logic;
    rematch008_taxi_out_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch008_taxi_out_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch008_taxi_out_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch009_taxi_out_valid        : out std_logic;
    rematch009_taxi_out_ready        : in  std_logic;
    rematch009_taxi_out_dvalid       : out std_logic;
    rematch009_taxi_out_last         : out std_logic;
    rematch009_taxi_out              : out std_logic_vector(31 downto 0);
    rematch009_taxi_out_unl_valid    : in  std_logic;
    rematch009_taxi_out_unl_ready    : out std_logic;
    rematch009_taxi_out_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch009_taxi_out_cmd_valid    : out std_logic;
    rematch009_taxi_out_cmd_ready    : in  std_logic;
    rematch009_taxi_out_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch009_taxi_out_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch009_taxi_out_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch010_taxi_out_valid        : out std_logic;
    rematch010_taxi_out_ready        : in  std_logic;
    rematch010_taxi_out_dvalid       : out std_logic;
    rematch010_taxi_out_last         : out std_logic;
    rematch010_taxi_out              : out std_logic_vector(31 downto 0);
    rematch010_taxi_out_unl_valid    : in  std_logic;
    rematch010_taxi_out_unl_ready    : out std_logic;
    rematch010_taxi_out_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch010_taxi_out_cmd_valid    : out std_logic;
    rematch010_taxi_out_cmd_ready    : in  std_logic;
    rematch010_taxi_out_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch010_taxi_out_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch010_taxi_out_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch011_taxi_out_valid        : out std_logic;
    rematch011_taxi_out_ready        : in  std_logic;
    rematch011_taxi_out_dvalid       : out std_logic;
    rematch011_taxi_out_last         : out std_logic;
    rematch011_taxi_out              : out std_logic_vector(31 downto 0);
    rematch011_taxi_out_unl_valid    : in  std_logic;
    rematch011_taxi_out_unl_ready    : out std_logic;
    rematch011_taxi_out_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch011_taxi_out_cmd_valid    : out std_logic;
    rematch011_taxi_out_cmd_ready    : in  std_logic;
    rematch011_taxi_out_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch011_taxi_out_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch011_taxi_out_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch012_taxi_out_valid        : out std_logic;
    rematch012_taxi_out_ready        : in  std_logic;
    rematch012_taxi_out_dvalid       : out std_logic;
    rematch012_taxi_out_last         : out std_logic;
    rematch012_taxi_out              : out std_logic_vector(31 downto 0);
    rematch012_taxi_out_unl_valid    : in  std_logic;
    rematch012_taxi_out_unl_ready    : out std_logic;
    rematch012_taxi_out_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch012_taxi_out_cmd_valid    : out std_logic;
    rematch012_taxi_out_cmd_ready    : in  std_logic;
    rematch012_taxi_out_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch012_taxi_out_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch012_taxi_out_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch013_taxi_out_valid        : out std_logic;
    rematch013_taxi_out_ready        : in  std_logic;
    rematch013_taxi_out_dvalid       : out std_logic;
    rematch013_taxi_out_last         : out std_logic;
    rematch013_taxi_out              : out std_logic_vector(31 downto 0);
    rematch013_taxi_out_unl_valid    : in  std_logic;
    rematch013_taxi_out_unl_ready    : out std_logic;
    rematch013_taxi_out_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch013_taxi_out_cmd_valid    : out std_logic;
    rematch013_taxi_out_cmd_ready    : in  std_logic;
    rematch013_taxi_out_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch013_taxi_out_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch013_taxi_out_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch014_taxi_out_valid        : out std_logic;
    rematch014_taxi_out_ready        : in  std_logic;
    rematch014_taxi_out_dvalid       : out std_logic;
    rematch014_taxi_out_last         : out std_logic;
    rematch014_taxi_out              : out std_logic_vector(31 downto 0);
    rematch014_taxi_out_unl_valid    : in  std_logic;
    rematch014_taxi_out_unl_ready    : out std_logic;
    rematch014_taxi_out_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch014_taxi_out_cmd_valid    : out std_logic;
    rematch014_taxi_out_cmd_ready    : in  std_logic;
    rematch014_taxi_out_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch014_taxi_out_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch014_taxi_out_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch015_taxi_out_valid        : out std_logic;
    rematch015_taxi_out_ready        : in  std_logic;
    rematch015_taxi_out_dvalid       : out std_logic;
    rematch015_taxi_out_last         : out std_logic;
    rematch015_taxi_out              : out std_logic_vector(31 downto 0);
    rematch015_taxi_out_unl_valid    : in  std_logic;
    rematch015_taxi_out_unl_ready    : out std_logic;
    rematch015_taxi_out_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch015_taxi_out_cmd_valid    : out std_logic;
    rematch015_taxi_out_cmd_ready    : in  std_logic;
    rematch015_taxi_out_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch015_taxi_out_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch015_taxi_out_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    start                            : in  std_logic;
    stop                             : in  std_logic;
    reset                            : in  std_logic;
    idle                             : out std_logic;
    busy                             : out std_logic;
    done                             : out std_logic;
    result                           : out std_logic_vector(63 downto 0);
    rematch000_firstidx              : in  std_logic_vector(31 downto 0);
    rematch000_lastidx               : in  std_logic_vector(31 downto 0);
    rematch001_firstidx              : in  std_logic_vector(31 downto 0);
    rematch001_lastidx               : in  std_logic_vector(31 downto 0);
    rematch002_firstidx              : in  std_logic_vector(31 downto 0);
    rematch002_lastidx               : in  std_logic_vector(31 downto 0);
    rematch003_firstidx              : in  std_logic_vector(31 downto 0);
    rematch003_lastidx               : in  std_logic_vector(31 downto 0);
    rematch004_firstidx              : in  std_logic_vector(31 downto 0);
    rematch004_lastidx               : in  std_logic_vector(31 downto 0);
    rematch005_firstidx              : in  std_logic_vector(31 downto 0);
    rematch005_lastidx               : in  std_logic_vector(31 downto 0);
    rematch006_firstidx              : in  std_logic_vector(31 downto 0);
    rematch006_lastidx               : in  std_logic_vector(31 downto 0);
    rematch007_firstidx              : in  std_logic_vector(31 downto 0);
    rematch007_lastidx               : in  std_logic_vector(31 downto 0);
    rematch008_firstidx              : in  std_logic_vector(31 downto 0);
    rematch008_lastidx               : in  std_logic_vector(31 downto 0);
    rematch009_firstidx              : in  std_logic_vector(31 downto 0);
    rematch009_lastidx               : in  std_logic_vector(31 downto 0);
    rematch010_firstidx              : in  std_logic_vector(31 downto 0);
    rematch010_lastidx               : in  std_logic_vector(31 downto 0);
    rematch011_firstidx              : in  std_logic_vector(31 downto 0);
    rematch011_lastidx               : in  std_logic_vector(31 downto 0);
    rematch012_firstidx              : in  std_logic_vector(31 downto 0);
    rematch012_lastidx               : in  std_logic_vector(31 downto 0);
    rematch013_firstidx              : in  std_logic_vector(31 downto 0);
    rematch013_lastidx               : in  std_logic_vector(31 downto 0);
    rematch014_firstidx              : in  std_logic_vector(31 downto 0);
    rematch014_lastidx               : in  std_logic_vector(31 downto 0);
    rematch015_firstidx              : in  std_logic_vector(31 downto 0);
    rematch015_lastidx               : in  std_logic_vector(31 downto 0);
    rematch000_taxi_firstidx         : in  std_logic_vector(31 downto 0);
    rematch000_taxi_lastidx          : in  std_logic_vector(31 downto 0);
    rematch001_taxi_firstidx         : in  std_logic_vector(31 downto 0);
    rematch001_taxi_lastidx          : in  std_logic_vector(31 downto 0);
    rematch002_taxi_firstidx         : in  std_logic_vector(31 downto 0);
    rematch002_taxi_lastidx          : in  std_logic_vector(31 downto 0);
    rematch003_taxi_firstidx         : in  std_logic_vector(31 downto 0);
    rematch003_taxi_lastidx          : in  std_logic_vector(31 downto 0);
    rematch004_taxi_firstidx         : in  std_logic_vector(31 downto 0);
    rematch004_taxi_lastidx          : in  std_logic_vector(31 downto 0);
    rematch005_taxi_firstidx         : in  std_logic_vector(31 downto 0);
    rematch005_taxi_lastidx          : in  std_logic_vector(31 downto 0);
    rematch006_taxi_firstidx         : in  std_logic_vector(31 downto 0);
    rematch006_taxi_lastidx          : in  std_logic_vector(31 downto 0);
    rematch007_taxi_firstidx         : in  std_logic_vector(31 downto 0);
    rematch007_taxi_lastidx          : in  std_logic_vector(31 downto 0);
    rematch008_taxi_firstidx         : in  std_logic_vector(31 downto 0);
    rematch008_taxi_lastidx          : in  std_logic_vector(31 downto 0);
    rematch009_taxi_firstidx         : in  std_logic_vector(31 downto 0);
    rematch009_taxi_lastidx          : in  std_logic_vector(31 downto 0);
    rematch010_taxi_firstidx         : in  std_logic_vector(31 downto 0);
    rematch010_taxi_lastidx          : in  std_logic_vector(31 downto 0);
    rematch011_taxi_firstidx         : in  std_logic_vector(31 downto 0);
    rematch011_taxi_lastidx          : in  std_logic_vector(31 downto 0);
    rematch012_taxi_firstidx         : in  std_logic_vector(31 downto 0);
    rematch012_taxi_lastidx          : in  std_logic_vector(31 downto 0);
    rematch013_taxi_firstidx         : in  std_logic_vector(31 downto 0);
    rematch013_taxi_lastidx          : in  std_logic_vector(31 downto 0);
    rematch014_taxi_firstidx         : in  std_logic_vector(31 downto 0);
    rematch014_taxi_lastidx          : in  std_logic_vector(31 downto 0);
    rematch015_taxi_firstidx         : in  std_logic_vector(31 downto 0);
    rematch015_taxi_lastidx          : in  std_logic_vector(31 downto 0);
    rematch000_taxi_count            : out std_logic_vector(31 downto 0);
    rematch000_errors                : out std_logic_vector(31 downto 0);
    rematch001_taxi_count            : out std_logic_vector(31 downto 0);
    rematch001_errors                : out std_logic_vector(31 downto 0);
    rematch002_taxi_count            : out std_logic_vector(31 downto 0);
    rematch002_errors                : out std_logic_vector(31 downto 0);
    rematch003_taxi_count            : out std_logic_vector(31 downto 0);
    rematch003_errors                : out std_logic_vector(31 downto 0);
    rematch004_taxi_count            : out std_logic_vector(31 downto 0);
    rematch004_errors                : out std_logic_vector(31 downto 0);
    rematch005_taxi_count            : out std_logic_vector(31 downto 0);
    rematch005_errors                : out std_logic_vector(31 downto 0);
    rematch006_taxi_count            : out std_logic_vector(31 downto 0);
    rematch006_errors                : out std_logic_vector(31 downto 0);
    rematch007_taxi_count            : out std_logic_vector(31 downto 0);
    rematch007_errors                : out std_logic_vector(31 downto 0);
    rematch008_taxi_count            : out std_logic_vector(31 downto 0);
    rematch008_errors                : out std_logic_vector(31 downto 0);
    rematch009_taxi_count            : out std_logic_vector(31 downto 0);
    rematch009_errors                : out std_logic_vector(31 downto 0);
    rematch010_taxi_count            : out std_logic_vector(31 downto 0);
    rematch010_errors                : out std_logic_vector(31 downto 0);
    rematch011_taxi_count            : out std_logic_vector(31 downto 0);
    rematch011_errors                : out std_logic_vector(31 downto 0);
    rematch012_taxi_count            : out std_logic_vector(31 downto 0);
    rematch012_errors                : out std_logic_vector(31 downto 0);
    rematch013_taxi_count            : out std_logic_vector(31 downto 0);
    rematch013_errors                : out std_logic_vector(31 downto 0);
    rematch014_taxi_count            : out std_logic_vector(31 downto 0);
    rematch014_errors                : out std_logic_vector(31 downto 0);
    rematch015_taxi_count            : out std_logic_vector(31 downto 0);
    rematch015_errors                : out std_logic_vector(31 downto 0)
  );
end entity;

architecture Implementation of Kernel is

  signal sub_idle   : std_logic_vector(16-1 downto 0);
  signal sub_busy   : std_logic_vector(16-1 downto 0);
  signal sub_done   : std_logic_vector(16-1 downto 0);

begin

  rematch000: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 1,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,

      -- Fletcher string reader interface.
      in_valid                 => rematch000_in_valid,
      in_ready                 => rematch000_in_ready,
      in_dvalid                => rematch000_in_dvalid,
      in_last                  => rematch000_in_last,
      in_length                => rematch000_in_length,
      in_count                 => rematch000_in_count,
      in_chars_valid           => rematch000_in_chars_valid,
      in_chars_ready           => rematch000_in_chars_ready,
      in_chars_dvalid          => rematch000_in_chars_dvalid,
      in_chars_last            => rematch000_in_chars_last,
      in_chars                 => rematch000_in_chars,
      in_chars_count           => rematch000_in_chars_count,
      in_unl_valid             => rematch000_in_unl_valid,
      in_unl_ready             => rematch000_in_unl_ready,
      in_unl_tag               => rematch000_in_unl_tag,
      in_cmd_valid             => rematch000_in_cmd_valid,
      in_cmd_ready             => rematch000_in_cmd_ready,
      in_cmd_firstIdx          => rematch000_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch000_in_cmd_lastIdx,
      in_cmd_tag               => rematch000_in_cmd_tag,

      -- Fletcher index writer interface for taxi.
      re_taxi_out_valid        => rematch000_taxi_out_valid,
      re_taxi_out_ready        => rematch000_taxi_out_ready,
      re_taxi_out_dvalid       => rematch000_taxi_out_dvalid,
      re_taxi_out_last         => rematch000_taxi_out_last,
      re_taxi_out              => rematch000_taxi_out,
      re_taxi_out_unl_valid    => rematch000_taxi_out_unl_valid,
      re_taxi_out_unl_ready    => rematch000_taxi_out_unl_ready,
      re_taxi_out_unl_tag      => rematch000_taxi_out_unl_tag,
      re_taxi_out_cmd_valid    => rematch000_taxi_out_cmd_valid,
      re_taxi_out_cmd_ready    => rematch000_taxi_out_cmd_ready,
      re_taxi_out_cmd_firstIdx => rematch000_taxi_out_cmd_firstIdx,
      re_taxi_out_cmd_lastIdx  => rematch000_taxi_out_cmd_lastIdx,
      re_taxi_out_cmd_tag      => rematch000_taxi_out_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(0),
      mmio_busy                => sub_busy(0),
      mmio_done                => sub_done(0),
      mmio_firstidx            => rematch000_firstidx,
      mmio_lastidx             => rematch000_lastidx,

      -- MMIO for taxi output buffer.
      mmio_re_taxi_firstidx => rematch000_taxi_firstidx,
      mmio_re_taxi_lastidx  => rematch000_taxi_lastidx,
      mmio_re_taxi_count    => rematch000_taxi_count,

      -- UTF-8 error counter output.
      mmio_errors              => rematch000_errors

    );

  rematch001: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 1,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,

      -- Fletcher string reader interface.
      in_valid                 => rematch001_in_valid,
      in_ready                 => rematch001_in_ready,
      in_dvalid                => rematch001_in_dvalid,
      in_last                  => rematch001_in_last,
      in_length                => rematch001_in_length,
      in_count                 => rematch001_in_count,
      in_chars_valid           => rematch001_in_chars_valid,
      in_chars_ready           => rematch001_in_chars_ready,
      in_chars_dvalid          => rematch001_in_chars_dvalid,
      in_chars_last            => rematch001_in_chars_last,
      in_chars                 => rematch001_in_chars,
      in_chars_count           => rematch001_in_chars_count,
      in_unl_valid             => rematch001_in_unl_valid,
      in_unl_ready             => rematch001_in_unl_ready,
      in_unl_tag               => rematch001_in_unl_tag,
      in_cmd_valid             => rematch001_in_cmd_valid,
      in_cmd_ready             => rematch001_in_cmd_ready,
      in_cmd_firstIdx          => rematch001_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch001_in_cmd_lastIdx,
      in_cmd_tag               => rematch001_in_cmd_tag,

      -- Fletcher index writer interface for taxi.
      re_taxi_out_valid        => rematch001_taxi_out_valid,
      re_taxi_out_ready        => rematch001_taxi_out_ready,
      re_taxi_out_dvalid       => rematch001_taxi_out_dvalid,
      re_taxi_out_last         => rematch001_taxi_out_last,
      re_taxi_out              => rematch001_taxi_out,
      re_taxi_out_unl_valid    => rematch001_taxi_out_unl_valid,
      re_taxi_out_unl_ready    => rematch001_taxi_out_unl_ready,
      re_taxi_out_unl_tag      => rematch001_taxi_out_unl_tag,
      re_taxi_out_cmd_valid    => rematch001_taxi_out_cmd_valid,
      re_taxi_out_cmd_ready    => rematch001_taxi_out_cmd_ready,
      re_taxi_out_cmd_firstIdx => rematch001_taxi_out_cmd_firstIdx,
      re_taxi_out_cmd_lastIdx  => rematch001_taxi_out_cmd_lastIdx,
      re_taxi_out_cmd_tag      => rematch001_taxi_out_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(1),
      mmio_busy                => sub_busy(1),
      mmio_done                => sub_done(1),
      mmio_firstidx            => rematch001_firstidx,
      mmio_lastidx             => rematch001_lastidx,

      -- MMIO for taxi output buffer.
      mmio_re_taxi_firstidx => rematch001_taxi_firstidx,
      mmio_re_taxi_lastidx  => rematch001_taxi_lastidx,
      mmio_re_taxi_count    => rematch001_taxi_count,

      -- UTF-8 error counter output.
      mmio_errors              => rematch001_errors

    );

  rematch002: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 1,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,

      -- Fletcher string reader interface.
      in_valid                 => rematch002_in_valid,
      in_ready                 => rematch002_in_ready,
      in_dvalid                => rematch002_in_dvalid,
      in_last                  => rematch002_in_last,
      in_length                => rematch002_in_length,
      in_count                 => rematch002_in_count,
      in_chars_valid           => rematch002_in_chars_valid,
      in_chars_ready           => rematch002_in_chars_ready,
      in_chars_dvalid          => rematch002_in_chars_dvalid,
      in_chars_last            => rematch002_in_chars_last,
      in_chars                 => rematch002_in_chars,
      in_chars_count           => rematch002_in_chars_count,
      in_unl_valid             => rematch002_in_unl_valid,
      in_unl_ready             => rematch002_in_unl_ready,
      in_unl_tag               => rematch002_in_unl_tag,
      in_cmd_valid             => rematch002_in_cmd_valid,
      in_cmd_ready             => rematch002_in_cmd_ready,
      in_cmd_firstIdx          => rematch002_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch002_in_cmd_lastIdx,
      in_cmd_tag               => rematch002_in_cmd_tag,

      -- Fletcher index writer interface for taxi.
      re_taxi_out_valid        => rematch002_taxi_out_valid,
      re_taxi_out_ready        => rematch002_taxi_out_ready,
      re_taxi_out_dvalid       => rematch002_taxi_out_dvalid,
      re_taxi_out_last         => rematch002_taxi_out_last,
      re_taxi_out              => rematch002_taxi_out,
      re_taxi_out_unl_valid    => rematch002_taxi_out_unl_valid,
      re_taxi_out_unl_ready    => rematch002_taxi_out_unl_ready,
      re_taxi_out_unl_tag      => rematch002_taxi_out_unl_tag,
      re_taxi_out_cmd_valid    => rematch002_taxi_out_cmd_valid,
      re_taxi_out_cmd_ready    => rematch002_taxi_out_cmd_ready,
      re_taxi_out_cmd_firstIdx => rematch002_taxi_out_cmd_firstIdx,
      re_taxi_out_cmd_lastIdx  => rematch002_taxi_out_cmd_lastIdx,
      re_taxi_out_cmd_tag      => rematch002_taxi_out_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(2),
      mmio_busy                => sub_busy(2),
      mmio_done                => sub_done(2),
      mmio_firstidx            => rematch002_firstidx,
      mmio_lastidx             => rematch002_lastidx,

      -- MMIO for taxi output buffer.
      mmio_re_taxi_firstidx => rematch002_taxi_firstidx,
      mmio_re_taxi_lastidx  => rematch002_taxi_lastidx,
      mmio_re_taxi_count    => rematch002_taxi_count,

      -- UTF-8 error counter output.
      mmio_errors              => rematch002_errors

    );

  rematch003: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 1,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,

      -- Fletcher string reader interface.
      in_valid                 => rematch003_in_valid,
      in_ready                 => rematch003_in_ready,
      in_dvalid                => rematch003_in_dvalid,
      in_last                  => rematch003_in_last,
      in_length                => rematch003_in_length,
      in_count                 => rematch003_in_count,
      in_chars_valid           => rematch003_in_chars_valid,
      in_chars_ready           => rematch003_in_chars_ready,
      in_chars_dvalid          => rematch003_in_chars_dvalid,
      in_chars_last            => rematch003_in_chars_last,
      in_chars                 => rematch003_in_chars,
      in_chars_count           => rematch003_in_chars_count,
      in_unl_valid             => rematch003_in_unl_valid,
      in_unl_ready             => rematch003_in_unl_ready,
      in_unl_tag               => rematch003_in_unl_tag,
      in_cmd_valid             => rematch003_in_cmd_valid,
      in_cmd_ready             => rematch003_in_cmd_ready,
      in_cmd_firstIdx          => rematch003_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch003_in_cmd_lastIdx,
      in_cmd_tag               => rematch003_in_cmd_tag,

      -- Fletcher index writer interface for taxi.
      re_taxi_out_valid        => rematch003_taxi_out_valid,
      re_taxi_out_ready        => rematch003_taxi_out_ready,
      re_taxi_out_dvalid       => rematch003_taxi_out_dvalid,
      re_taxi_out_last         => rematch003_taxi_out_last,
      re_taxi_out              => rematch003_taxi_out,
      re_taxi_out_unl_valid    => rematch003_taxi_out_unl_valid,
      re_taxi_out_unl_ready    => rematch003_taxi_out_unl_ready,
      re_taxi_out_unl_tag      => rematch003_taxi_out_unl_tag,
      re_taxi_out_cmd_valid    => rematch003_taxi_out_cmd_valid,
      re_taxi_out_cmd_ready    => rematch003_taxi_out_cmd_ready,
      re_taxi_out_cmd_firstIdx => rematch003_taxi_out_cmd_firstIdx,
      re_taxi_out_cmd_lastIdx  => rematch003_taxi_out_cmd_lastIdx,
      re_taxi_out_cmd_tag      => rematch003_taxi_out_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(3),
      mmio_busy                => sub_busy(3),
      mmio_done                => sub_done(3),
      mmio_firstidx            => rematch003_firstidx,
      mmio_lastidx             => rematch003_lastidx,

      -- MMIO for taxi output buffer.
      mmio_re_taxi_firstidx => rematch003_taxi_firstidx,
      mmio_re_taxi_lastidx  => rematch003_taxi_lastidx,
      mmio_re_taxi_count    => rematch003_taxi_count,

      -- UTF-8 error counter output.
      mmio_errors              => rematch003_errors

    );

  rematch004: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 1,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,

      -- Fletcher string reader interface.
      in_valid                 => rematch004_in_valid,
      in_ready                 => rematch004_in_ready,
      in_dvalid                => rematch004_in_dvalid,
      in_last                  => rematch004_in_last,
      in_length                => rematch004_in_length,
      in_count                 => rematch004_in_count,
      in_chars_valid           => rematch004_in_chars_valid,
      in_chars_ready           => rematch004_in_chars_ready,
      in_chars_dvalid          => rematch004_in_chars_dvalid,
      in_chars_last            => rematch004_in_chars_last,
      in_chars                 => rematch004_in_chars,
      in_chars_count           => rematch004_in_chars_count,
      in_unl_valid             => rematch004_in_unl_valid,
      in_unl_ready             => rematch004_in_unl_ready,
      in_unl_tag               => rematch004_in_unl_tag,
      in_cmd_valid             => rematch004_in_cmd_valid,
      in_cmd_ready             => rematch004_in_cmd_ready,
      in_cmd_firstIdx          => rematch004_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch004_in_cmd_lastIdx,
      in_cmd_tag               => rematch004_in_cmd_tag,

      -- Fletcher index writer interface for taxi.
      re_taxi_out_valid        => rematch004_taxi_out_valid,
      re_taxi_out_ready        => rematch004_taxi_out_ready,
      re_taxi_out_dvalid       => rematch004_taxi_out_dvalid,
      re_taxi_out_last         => rematch004_taxi_out_last,
      re_taxi_out              => rematch004_taxi_out,
      re_taxi_out_unl_valid    => rematch004_taxi_out_unl_valid,
      re_taxi_out_unl_ready    => rematch004_taxi_out_unl_ready,
      re_taxi_out_unl_tag      => rematch004_taxi_out_unl_tag,
      re_taxi_out_cmd_valid    => rematch004_taxi_out_cmd_valid,
      re_taxi_out_cmd_ready    => rematch004_taxi_out_cmd_ready,
      re_taxi_out_cmd_firstIdx => rematch004_taxi_out_cmd_firstIdx,
      re_taxi_out_cmd_lastIdx  => rematch004_taxi_out_cmd_lastIdx,
      re_taxi_out_cmd_tag      => rematch004_taxi_out_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(4),
      mmio_busy                => sub_busy(4),
      mmio_done                => sub_done(4),
      mmio_firstidx            => rematch004_firstidx,
      mmio_lastidx             => rematch004_lastidx,

      -- MMIO for taxi output buffer.
      mmio_re_taxi_firstidx => rematch004_taxi_firstidx,
      mmio_re_taxi_lastidx  => rematch004_taxi_lastidx,
      mmio_re_taxi_count    => rematch004_taxi_count,

      -- UTF-8 error counter output.
      mmio_errors              => rematch004_errors

    );

  rematch005: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 1,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,

      -- Fletcher string reader interface.
      in_valid                 => rematch005_in_valid,
      in_ready                 => rematch005_in_ready,
      in_dvalid                => rematch005_in_dvalid,
      in_last                  => rematch005_in_last,
      in_length                => rematch005_in_length,
      in_count                 => rematch005_in_count,
      in_chars_valid           => rematch005_in_chars_valid,
      in_chars_ready           => rematch005_in_chars_ready,
      in_chars_dvalid          => rematch005_in_chars_dvalid,
      in_chars_last            => rematch005_in_chars_last,
      in_chars                 => rematch005_in_chars,
      in_chars_count           => rematch005_in_chars_count,
      in_unl_valid             => rematch005_in_unl_valid,
      in_unl_ready             => rematch005_in_unl_ready,
      in_unl_tag               => rematch005_in_unl_tag,
      in_cmd_valid             => rematch005_in_cmd_valid,
      in_cmd_ready             => rematch005_in_cmd_ready,
      in_cmd_firstIdx          => rematch005_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch005_in_cmd_lastIdx,
      in_cmd_tag               => rematch005_in_cmd_tag,

      -- Fletcher index writer interface for taxi.
      re_taxi_out_valid        => rematch005_taxi_out_valid,
      re_taxi_out_ready        => rematch005_taxi_out_ready,
      re_taxi_out_dvalid       => rematch005_taxi_out_dvalid,
      re_taxi_out_last         => rematch005_taxi_out_last,
      re_taxi_out              => rematch005_taxi_out,
      re_taxi_out_unl_valid    => rematch005_taxi_out_unl_valid,
      re_taxi_out_unl_ready    => rematch005_taxi_out_unl_ready,
      re_taxi_out_unl_tag      => rematch005_taxi_out_unl_tag,
      re_taxi_out_cmd_valid    => rematch005_taxi_out_cmd_valid,
      re_taxi_out_cmd_ready    => rematch005_taxi_out_cmd_ready,
      re_taxi_out_cmd_firstIdx => rematch005_taxi_out_cmd_firstIdx,
      re_taxi_out_cmd_lastIdx  => rematch005_taxi_out_cmd_lastIdx,
      re_taxi_out_cmd_tag      => rematch005_taxi_out_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(5),
      mmio_busy                => sub_busy(5),
      mmio_done                => sub_done(5),
      mmio_firstidx            => rematch005_firstidx,
      mmio_lastidx             => rematch005_lastidx,

      -- MMIO for taxi output buffer.
      mmio_re_taxi_firstidx => rematch005_taxi_firstidx,
      mmio_re_taxi_lastidx  => rematch005_taxi_lastidx,
      mmio_re_taxi_count    => rematch005_taxi_count,

      -- UTF-8 error counter output.
      mmio_errors              => rematch005_errors

    );

  rematch006: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 1,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,

      -- Fletcher string reader interface.
      in_valid                 => rematch006_in_valid,
      in_ready                 => rematch006_in_ready,
      in_dvalid                => rematch006_in_dvalid,
      in_last                  => rematch006_in_last,
      in_length                => rematch006_in_length,
      in_count                 => rematch006_in_count,
      in_chars_valid           => rematch006_in_chars_valid,
      in_chars_ready           => rematch006_in_chars_ready,
      in_chars_dvalid          => rematch006_in_chars_dvalid,
      in_chars_last            => rematch006_in_chars_last,
      in_chars                 => rematch006_in_chars,
      in_chars_count           => rematch006_in_chars_count,
      in_unl_valid             => rematch006_in_unl_valid,
      in_unl_ready             => rematch006_in_unl_ready,
      in_unl_tag               => rematch006_in_unl_tag,
      in_cmd_valid             => rematch006_in_cmd_valid,
      in_cmd_ready             => rematch006_in_cmd_ready,
      in_cmd_firstIdx          => rematch006_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch006_in_cmd_lastIdx,
      in_cmd_tag               => rematch006_in_cmd_tag,

      -- Fletcher index writer interface for taxi.
      re_taxi_out_valid        => rematch006_taxi_out_valid,
      re_taxi_out_ready        => rematch006_taxi_out_ready,
      re_taxi_out_dvalid       => rematch006_taxi_out_dvalid,
      re_taxi_out_last         => rematch006_taxi_out_last,
      re_taxi_out              => rematch006_taxi_out,
      re_taxi_out_unl_valid    => rematch006_taxi_out_unl_valid,
      re_taxi_out_unl_ready    => rematch006_taxi_out_unl_ready,
      re_taxi_out_unl_tag      => rematch006_taxi_out_unl_tag,
      re_taxi_out_cmd_valid    => rematch006_taxi_out_cmd_valid,
      re_taxi_out_cmd_ready    => rematch006_taxi_out_cmd_ready,
      re_taxi_out_cmd_firstIdx => rematch006_taxi_out_cmd_firstIdx,
      re_taxi_out_cmd_lastIdx  => rematch006_taxi_out_cmd_lastIdx,
      re_taxi_out_cmd_tag      => rematch006_taxi_out_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(6),
      mmio_busy                => sub_busy(6),
      mmio_done                => sub_done(6),
      mmio_firstidx            => rematch006_firstidx,
      mmio_lastidx             => rematch006_lastidx,

      -- MMIO for taxi output buffer.
      mmio_re_taxi_firstidx => rematch006_taxi_firstidx,
      mmio_re_taxi_lastidx  => rematch006_taxi_lastidx,
      mmio_re_taxi_count    => rematch006_taxi_count,

      -- UTF-8 error counter output.
      mmio_errors              => rematch006_errors

    );

  rematch007: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 1,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,

      -- Fletcher string reader interface.
      in_valid                 => rematch007_in_valid,
      in_ready                 => rematch007_in_ready,
      in_dvalid                => rematch007_in_dvalid,
      in_last                  => rematch007_in_last,
      in_length                => rematch007_in_length,
      in_count                 => rematch007_in_count,
      in_chars_valid           => rematch007_in_chars_valid,
      in_chars_ready           => rematch007_in_chars_ready,
      in_chars_dvalid          => rematch007_in_chars_dvalid,
      in_chars_last            => rematch007_in_chars_last,
      in_chars                 => rematch007_in_chars,
      in_chars_count           => rematch007_in_chars_count,
      in_unl_valid             => rematch007_in_unl_valid,
      in_unl_ready             => rematch007_in_unl_ready,
      in_unl_tag               => rematch007_in_unl_tag,
      in_cmd_valid             => rematch007_in_cmd_valid,
      in_cmd_ready             => rematch007_in_cmd_ready,
      in_cmd_firstIdx          => rematch007_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch007_in_cmd_lastIdx,
      in_cmd_tag               => rematch007_in_cmd_tag,

      -- Fletcher index writer interface for taxi.
      re_taxi_out_valid        => rematch007_taxi_out_valid,
      re_taxi_out_ready        => rematch007_taxi_out_ready,
      re_taxi_out_dvalid       => rematch007_taxi_out_dvalid,
      re_taxi_out_last         => rematch007_taxi_out_last,
      re_taxi_out              => rematch007_taxi_out,
      re_taxi_out_unl_valid    => rematch007_taxi_out_unl_valid,
      re_taxi_out_unl_ready    => rematch007_taxi_out_unl_ready,
      re_taxi_out_unl_tag      => rematch007_taxi_out_unl_tag,
      re_taxi_out_cmd_valid    => rematch007_taxi_out_cmd_valid,
      re_taxi_out_cmd_ready    => rematch007_taxi_out_cmd_ready,
      re_taxi_out_cmd_firstIdx => rematch007_taxi_out_cmd_firstIdx,
      re_taxi_out_cmd_lastIdx  => rematch007_taxi_out_cmd_lastIdx,
      re_taxi_out_cmd_tag      => rematch007_taxi_out_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(7),
      mmio_busy                => sub_busy(7),
      mmio_done                => sub_done(7),
      mmio_firstidx            => rematch007_firstidx,
      mmio_lastidx             => rematch007_lastidx,

      -- MMIO for taxi output buffer.
      mmio_re_taxi_firstidx => rematch007_taxi_firstidx,
      mmio_re_taxi_lastidx  => rematch007_taxi_lastidx,
      mmio_re_taxi_count    => rematch007_taxi_count,

      -- UTF-8 error counter output.
      mmio_errors              => rematch007_errors

    );

  rematch008: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 1,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,

      -- Fletcher string reader interface.
      in_valid                 => rematch008_in_valid,
      in_ready                 => rematch008_in_ready,
      in_dvalid                => rematch008_in_dvalid,
      in_last                  => rematch008_in_last,
      in_length                => rematch008_in_length,
      in_count                 => rematch008_in_count,
      in_chars_valid           => rematch008_in_chars_valid,
      in_chars_ready           => rematch008_in_chars_ready,
      in_chars_dvalid          => rematch008_in_chars_dvalid,
      in_chars_last            => rematch008_in_chars_last,
      in_chars                 => rematch008_in_chars,
      in_chars_count           => rematch008_in_chars_count,
      in_unl_valid             => rematch008_in_unl_valid,
      in_unl_ready             => rematch008_in_unl_ready,
      in_unl_tag               => rematch008_in_unl_tag,
      in_cmd_valid             => rematch008_in_cmd_valid,
      in_cmd_ready             => rematch008_in_cmd_ready,
      in_cmd_firstIdx          => rematch008_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch008_in_cmd_lastIdx,
      in_cmd_tag               => rematch008_in_cmd_tag,

      -- Fletcher index writer interface for taxi.
      re_taxi_out_valid        => rematch008_taxi_out_valid,
      re_taxi_out_ready        => rematch008_taxi_out_ready,
      re_taxi_out_dvalid       => rematch008_taxi_out_dvalid,
      re_taxi_out_last         => rematch008_taxi_out_last,
      re_taxi_out              => rematch008_taxi_out,
      re_taxi_out_unl_valid    => rematch008_taxi_out_unl_valid,
      re_taxi_out_unl_ready    => rematch008_taxi_out_unl_ready,
      re_taxi_out_unl_tag      => rematch008_taxi_out_unl_tag,
      re_taxi_out_cmd_valid    => rematch008_taxi_out_cmd_valid,
      re_taxi_out_cmd_ready    => rematch008_taxi_out_cmd_ready,
      re_taxi_out_cmd_firstIdx => rematch008_taxi_out_cmd_firstIdx,
      re_taxi_out_cmd_lastIdx  => rematch008_taxi_out_cmd_lastIdx,
      re_taxi_out_cmd_tag      => rematch008_taxi_out_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(8),
      mmio_busy                => sub_busy(8),
      mmio_done                => sub_done(8),
      mmio_firstidx            => rematch008_firstidx,
      mmio_lastidx             => rematch008_lastidx,

      -- MMIO for taxi output buffer.
      mmio_re_taxi_firstidx => rematch008_taxi_firstidx,
      mmio_re_taxi_lastidx  => rematch008_taxi_lastidx,
      mmio_re_taxi_count    => rematch008_taxi_count,

      -- UTF-8 error counter output.
      mmio_errors              => rematch008_errors

    );

  rematch009: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 1,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,

      -- Fletcher string reader interface.
      in_valid                 => rematch009_in_valid,
      in_ready                 => rematch009_in_ready,
      in_dvalid                => rematch009_in_dvalid,
      in_last                  => rematch009_in_last,
      in_length                => rematch009_in_length,
      in_count                 => rematch009_in_count,
      in_chars_valid           => rematch009_in_chars_valid,
      in_chars_ready           => rematch009_in_chars_ready,
      in_chars_dvalid          => rematch009_in_chars_dvalid,
      in_chars_last            => rematch009_in_chars_last,
      in_chars                 => rematch009_in_chars,
      in_chars_count           => rematch009_in_chars_count,
      in_unl_valid             => rematch009_in_unl_valid,
      in_unl_ready             => rematch009_in_unl_ready,
      in_unl_tag               => rematch009_in_unl_tag,
      in_cmd_valid             => rematch009_in_cmd_valid,
      in_cmd_ready             => rematch009_in_cmd_ready,
      in_cmd_firstIdx          => rematch009_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch009_in_cmd_lastIdx,
      in_cmd_tag               => rematch009_in_cmd_tag,

      -- Fletcher index writer interface for taxi.
      re_taxi_out_valid        => rematch009_taxi_out_valid,
      re_taxi_out_ready        => rematch009_taxi_out_ready,
      re_taxi_out_dvalid       => rematch009_taxi_out_dvalid,
      re_taxi_out_last         => rematch009_taxi_out_last,
      re_taxi_out              => rematch009_taxi_out,
      re_taxi_out_unl_valid    => rematch009_taxi_out_unl_valid,
      re_taxi_out_unl_ready    => rematch009_taxi_out_unl_ready,
      re_taxi_out_unl_tag      => rematch009_taxi_out_unl_tag,
      re_taxi_out_cmd_valid    => rematch009_taxi_out_cmd_valid,
      re_taxi_out_cmd_ready    => rematch009_taxi_out_cmd_ready,
      re_taxi_out_cmd_firstIdx => rematch009_taxi_out_cmd_firstIdx,
      re_taxi_out_cmd_lastIdx  => rematch009_taxi_out_cmd_lastIdx,
      re_taxi_out_cmd_tag      => rematch009_taxi_out_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(9),
      mmio_busy                => sub_busy(9),
      mmio_done                => sub_done(9),
      mmio_firstidx            => rematch009_firstidx,
      mmio_lastidx             => rematch009_lastidx,

      -- MMIO for taxi output buffer.
      mmio_re_taxi_firstidx => rematch009_taxi_firstidx,
      mmio_re_taxi_lastidx  => rematch009_taxi_lastidx,
      mmio_re_taxi_count    => rematch009_taxi_count,

      -- UTF-8 error counter output.
      mmio_errors              => rematch009_errors

    );

  rematch010: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 1,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,

      -- Fletcher string reader interface.
      in_valid                 => rematch010_in_valid,
      in_ready                 => rematch010_in_ready,
      in_dvalid                => rematch010_in_dvalid,
      in_last                  => rematch010_in_last,
      in_length                => rematch010_in_length,
      in_count                 => rematch010_in_count,
      in_chars_valid           => rematch010_in_chars_valid,
      in_chars_ready           => rematch010_in_chars_ready,
      in_chars_dvalid          => rematch010_in_chars_dvalid,
      in_chars_last            => rematch010_in_chars_last,
      in_chars                 => rematch010_in_chars,
      in_chars_count           => rematch010_in_chars_count,
      in_unl_valid             => rematch010_in_unl_valid,
      in_unl_ready             => rematch010_in_unl_ready,
      in_unl_tag               => rematch010_in_unl_tag,
      in_cmd_valid             => rematch010_in_cmd_valid,
      in_cmd_ready             => rematch010_in_cmd_ready,
      in_cmd_firstIdx          => rematch010_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch010_in_cmd_lastIdx,
      in_cmd_tag               => rematch010_in_cmd_tag,

      -- Fletcher index writer interface for taxi.
      re_taxi_out_valid        => rematch010_taxi_out_valid,
      re_taxi_out_ready        => rematch010_taxi_out_ready,
      re_taxi_out_dvalid       => rematch010_taxi_out_dvalid,
      re_taxi_out_last         => rematch010_taxi_out_last,
      re_taxi_out              => rematch010_taxi_out,
      re_taxi_out_unl_valid    => rematch010_taxi_out_unl_valid,
      re_taxi_out_unl_ready    => rematch010_taxi_out_unl_ready,
      re_taxi_out_unl_tag      => rematch010_taxi_out_unl_tag,
      re_taxi_out_cmd_valid    => rematch010_taxi_out_cmd_valid,
      re_taxi_out_cmd_ready    => rematch010_taxi_out_cmd_ready,
      re_taxi_out_cmd_firstIdx => rematch010_taxi_out_cmd_firstIdx,
      re_taxi_out_cmd_lastIdx  => rematch010_taxi_out_cmd_lastIdx,
      re_taxi_out_cmd_tag      => rematch010_taxi_out_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(10),
      mmio_busy                => sub_busy(10),
      mmio_done                => sub_done(10),
      mmio_firstidx            => rematch010_firstidx,
      mmio_lastidx             => rematch010_lastidx,

      -- MMIO for taxi output buffer.
      mmio_re_taxi_firstidx => rematch010_taxi_firstidx,
      mmio_re_taxi_lastidx  => rematch010_taxi_lastidx,
      mmio_re_taxi_count    => rematch010_taxi_count,

      -- UTF-8 error counter output.
      mmio_errors              => rematch010_errors

    );

  rematch011: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 1,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,

      -- Fletcher string reader interface.
      in_valid                 => rematch011_in_valid,
      in_ready                 => rematch011_in_ready,
      in_dvalid                => rematch011_in_dvalid,
      in_last                  => rematch011_in_last,
      in_length                => rematch011_in_length,
      in_count                 => rematch011_in_count,
      in_chars_valid           => rematch011_in_chars_valid,
      in_chars_ready           => rematch011_in_chars_ready,
      in_chars_dvalid          => rematch011_in_chars_dvalid,
      in_chars_last            => rematch011_in_chars_last,
      in_chars                 => rematch011_in_chars,
      in_chars_count           => rematch011_in_chars_count,
      in_unl_valid             => rematch011_in_unl_valid,
      in_unl_ready             => rematch011_in_unl_ready,
      in_unl_tag               => rematch011_in_unl_tag,
      in_cmd_valid             => rematch011_in_cmd_valid,
      in_cmd_ready             => rematch011_in_cmd_ready,
      in_cmd_firstIdx          => rematch011_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch011_in_cmd_lastIdx,
      in_cmd_tag               => rematch011_in_cmd_tag,

      -- Fletcher index writer interface for taxi.
      re_taxi_out_valid        => rematch011_taxi_out_valid,
      re_taxi_out_ready        => rematch011_taxi_out_ready,
      re_taxi_out_dvalid       => rematch011_taxi_out_dvalid,
      re_taxi_out_last         => rematch011_taxi_out_last,
      re_taxi_out              => rematch011_taxi_out,
      re_taxi_out_unl_valid    => rematch011_taxi_out_unl_valid,
      re_taxi_out_unl_ready    => rematch011_taxi_out_unl_ready,
      re_taxi_out_unl_tag      => rematch011_taxi_out_unl_tag,
      re_taxi_out_cmd_valid    => rematch011_taxi_out_cmd_valid,
      re_taxi_out_cmd_ready    => rematch011_taxi_out_cmd_ready,
      re_taxi_out_cmd_firstIdx => rematch011_taxi_out_cmd_firstIdx,
      re_taxi_out_cmd_lastIdx  => rematch011_taxi_out_cmd_lastIdx,
      re_taxi_out_cmd_tag      => rematch011_taxi_out_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(11),
      mmio_busy                => sub_busy(11),
      mmio_done                => sub_done(11),
      mmio_firstidx            => rematch011_firstidx,
      mmio_lastidx             => rematch011_lastidx,

      -- MMIO for taxi output buffer.
      mmio_re_taxi_firstidx => rematch011_taxi_firstidx,
      mmio_re_taxi_lastidx  => rematch011_taxi_lastidx,
      mmio_re_taxi_count    => rematch011_taxi_count,

      -- UTF-8 error counter output.
      mmio_errors              => rematch011_errors

    );

  rematch012: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 1,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,

      -- Fletcher string reader interface.
      in_valid                 => rematch012_in_valid,
      in_ready                 => rematch012_in_ready,
      in_dvalid                => rematch012_in_dvalid,
      in_last                  => rematch012_in_last,
      in_length                => rematch012_in_length,
      in_count                 => rematch012_in_count,
      in_chars_valid           => rematch012_in_chars_valid,
      in_chars_ready           => rematch012_in_chars_ready,
      in_chars_dvalid          => rematch012_in_chars_dvalid,
      in_chars_last            => rematch012_in_chars_last,
      in_chars                 => rematch012_in_chars,
      in_chars_count           => rematch012_in_chars_count,
      in_unl_valid             => rematch012_in_unl_valid,
      in_unl_ready             => rematch012_in_unl_ready,
      in_unl_tag               => rematch012_in_unl_tag,
      in_cmd_valid             => rematch012_in_cmd_valid,
      in_cmd_ready             => rematch012_in_cmd_ready,
      in_cmd_firstIdx          => rematch012_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch012_in_cmd_lastIdx,
      in_cmd_tag               => rematch012_in_cmd_tag,

      -- Fletcher index writer interface for taxi.
      re_taxi_out_valid        => rematch012_taxi_out_valid,
      re_taxi_out_ready        => rematch012_taxi_out_ready,
      re_taxi_out_dvalid       => rematch012_taxi_out_dvalid,
      re_taxi_out_last         => rematch012_taxi_out_last,
      re_taxi_out              => rematch012_taxi_out,
      re_taxi_out_unl_valid    => rematch012_taxi_out_unl_valid,
      re_taxi_out_unl_ready    => rematch012_taxi_out_unl_ready,
      re_taxi_out_unl_tag      => rematch012_taxi_out_unl_tag,
      re_taxi_out_cmd_valid    => rematch012_taxi_out_cmd_valid,
      re_taxi_out_cmd_ready    => rematch012_taxi_out_cmd_ready,
      re_taxi_out_cmd_firstIdx => rematch012_taxi_out_cmd_firstIdx,
      re_taxi_out_cmd_lastIdx  => rematch012_taxi_out_cmd_lastIdx,
      re_taxi_out_cmd_tag      => rematch012_taxi_out_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(12),
      mmio_busy                => sub_busy(12),
      mmio_done                => sub_done(12),
      mmio_firstidx            => rematch012_firstidx,
      mmio_lastidx             => rematch012_lastidx,

      -- MMIO for taxi output buffer.
      mmio_re_taxi_firstidx => rematch012_taxi_firstidx,
      mmio_re_taxi_lastidx  => rematch012_taxi_lastidx,
      mmio_re_taxi_count    => rematch012_taxi_count,

      -- UTF-8 error counter output.
      mmio_errors              => rematch012_errors

    );

  rematch013: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 1,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,

      -- Fletcher string reader interface.
      in_valid                 => rematch013_in_valid,
      in_ready                 => rematch013_in_ready,
      in_dvalid                => rematch013_in_dvalid,
      in_last                  => rematch013_in_last,
      in_length                => rematch013_in_length,
      in_count                 => rematch013_in_count,
      in_chars_valid           => rematch013_in_chars_valid,
      in_chars_ready           => rematch013_in_chars_ready,
      in_chars_dvalid          => rematch013_in_chars_dvalid,
      in_chars_last            => rematch013_in_chars_last,
      in_chars                 => rematch013_in_chars,
      in_chars_count           => rematch013_in_chars_count,
      in_unl_valid             => rematch013_in_unl_valid,
      in_unl_ready             => rematch013_in_unl_ready,
      in_unl_tag               => rematch013_in_unl_tag,
      in_cmd_valid             => rematch013_in_cmd_valid,
      in_cmd_ready             => rematch013_in_cmd_ready,
      in_cmd_firstIdx          => rematch013_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch013_in_cmd_lastIdx,
      in_cmd_tag               => rematch013_in_cmd_tag,

      -- Fletcher index writer interface for taxi.
      re_taxi_out_valid        => rematch013_taxi_out_valid,
      re_taxi_out_ready        => rematch013_taxi_out_ready,
      re_taxi_out_dvalid       => rematch013_taxi_out_dvalid,
      re_taxi_out_last         => rematch013_taxi_out_last,
      re_taxi_out              => rematch013_taxi_out,
      re_taxi_out_unl_valid    => rematch013_taxi_out_unl_valid,
      re_taxi_out_unl_ready    => rematch013_taxi_out_unl_ready,
      re_taxi_out_unl_tag      => rematch013_taxi_out_unl_tag,
      re_taxi_out_cmd_valid    => rematch013_taxi_out_cmd_valid,
      re_taxi_out_cmd_ready    => rematch013_taxi_out_cmd_ready,
      re_taxi_out_cmd_firstIdx => rematch013_taxi_out_cmd_firstIdx,
      re_taxi_out_cmd_lastIdx  => rematch013_taxi_out_cmd_lastIdx,
      re_taxi_out_cmd_tag      => rematch013_taxi_out_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(13),
      mmio_busy                => sub_busy(13),
      mmio_done                => sub_done(13),
      mmio_firstidx            => rematch013_firstidx,
      mmio_lastidx             => rematch013_lastidx,

      -- MMIO for taxi output buffer.
      mmio_re_taxi_firstidx => rematch013_taxi_firstidx,
      mmio_re_taxi_lastidx  => rematch013_taxi_lastidx,
      mmio_re_taxi_count    => rematch013_taxi_count,

      -- UTF-8 error counter output.
      mmio_errors              => rematch013_errors

    );

  rematch014: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 1,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,

      -- Fletcher string reader interface.
      in_valid                 => rematch014_in_valid,
      in_ready                 => rematch014_in_ready,
      in_dvalid                => rematch014_in_dvalid,
      in_last                  => rematch014_in_last,
      in_length                => rematch014_in_length,
      in_count                 => rematch014_in_count,
      in_chars_valid           => rematch014_in_chars_valid,
      in_chars_ready           => rematch014_in_chars_ready,
      in_chars_dvalid          => rematch014_in_chars_dvalid,
      in_chars_last            => rematch014_in_chars_last,
      in_chars                 => rematch014_in_chars,
      in_chars_count           => rematch014_in_chars_count,
      in_unl_valid             => rematch014_in_unl_valid,
      in_unl_ready             => rematch014_in_unl_ready,
      in_unl_tag               => rematch014_in_unl_tag,
      in_cmd_valid             => rematch014_in_cmd_valid,
      in_cmd_ready             => rematch014_in_cmd_ready,
      in_cmd_firstIdx          => rematch014_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch014_in_cmd_lastIdx,
      in_cmd_tag               => rematch014_in_cmd_tag,

      -- Fletcher index writer interface for taxi.
      re_taxi_out_valid        => rematch014_taxi_out_valid,
      re_taxi_out_ready        => rematch014_taxi_out_ready,
      re_taxi_out_dvalid       => rematch014_taxi_out_dvalid,
      re_taxi_out_last         => rematch014_taxi_out_last,
      re_taxi_out              => rematch014_taxi_out,
      re_taxi_out_unl_valid    => rematch014_taxi_out_unl_valid,
      re_taxi_out_unl_ready    => rematch014_taxi_out_unl_ready,
      re_taxi_out_unl_tag      => rematch014_taxi_out_unl_tag,
      re_taxi_out_cmd_valid    => rematch014_taxi_out_cmd_valid,
      re_taxi_out_cmd_ready    => rematch014_taxi_out_cmd_ready,
      re_taxi_out_cmd_firstIdx => rematch014_taxi_out_cmd_firstIdx,
      re_taxi_out_cmd_lastIdx  => rematch014_taxi_out_cmd_lastIdx,
      re_taxi_out_cmd_tag      => rematch014_taxi_out_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(14),
      mmio_busy                => sub_busy(14),
      mmio_done                => sub_done(14),
      mmio_firstidx            => rematch014_firstidx,
      mmio_lastidx             => rematch014_lastidx,

      -- MMIO for taxi output buffer.
      mmio_re_taxi_firstidx => rematch014_taxi_firstidx,
      mmio_re_taxi_lastidx  => rematch014_taxi_lastidx,
      mmio_re_taxi_count    => rematch014_taxi_count,

      -- UTF-8 error counter output.
      mmio_errors              => rematch014_errors

    );

  rematch015: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 1,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,

      -- Fletcher string reader interface.
      in_valid                 => rematch015_in_valid,
      in_ready                 => rematch015_in_ready,
      in_dvalid                => rematch015_in_dvalid,
      in_last                  => rematch015_in_last,
      in_length                => rematch015_in_length,
      in_count                 => rematch015_in_count,
      in_chars_valid           => rematch015_in_chars_valid,
      in_chars_ready           => rematch015_in_chars_ready,
      in_chars_dvalid          => rematch015_in_chars_dvalid,
      in_chars_last            => rematch015_in_chars_last,
      in_chars                 => rematch015_in_chars,
      in_chars_count           => rematch015_in_chars_count,
      in_unl_valid             => rematch015_in_unl_valid,
      in_unl_ready             => rematch015_in_unl_ready,
      in_unl_tag               => rematch015_in_unl_tag,
      in_cmd_valid             => rematch015_in_cmd_valid,
      in_cmd_ready             => rematch015_in_cmd_ready,
      in_cmd_firstIdx          => rematch015_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch015_in_cmd_lastIdx,
      in_cmd_tag               => rematch015_in_cmd_tag,

      -- Fletcher index writer interface for taxi.
      re_taxi_out_valid        => rematch015_taxi_out_valid,
      re_taxi_out_ready        => rematch015_taxi_out_ready,
      re_taxi_out_dvalid       => rematch015_taxi_out_dvalid,
      re_taxi_out_last         => rematch015_taxi_out_last,
      re_taxi_out              => rematch015_taxi_out,
      re_taxi_out_unl_valid    => rematch015_taxi_out_unl_valid,
      re_taxi_out_unl_ready    => rematch015_taxi_out_unl_ready,
      re_taxi_out_unl_tag      => rematch015_taxi_out_unl_tag,
      re_taxi_out_cmd_valid    => rematch015_taxi_out_cmd_valid,
      re_taxi_out_cmd_ready    => rematch015_taxi_out_cmd_ready,
      re_taxi_out_cmd_firstIdx => rematch015_taxi_out_cmd_firstIdx,
      re_taxi_out_cmd_lastIdx  => rematch015_taxi_out_cmd_lastIdx,
      re_taxi_out_cmd_tag      => rematch015_taxi_out_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(15),
      mmio_busy                => sub_busy(15),
      mmio_done                => sub_done(15),
      mmio_firstidx            => rematch015_firstidx,
      mmio_lastidx             => rematch015_lastidx,

      -- MMIO for taxi output buffer.
      mmio_re_taxi_firstidx => rematch015_taxi_firstidx,
      mmio_re_taxi_lastidx  => rematch015_taxi_lastidx,
      mmio_re_taxi_count    => rematch015_taxi_count,

      -- UTF-8 error counter output.
      mmio_errors              => rematch015_errors

    );

  proc: process (kcd_clk) is
  begin
    if rising_edge(kcd_clk) then
      idle <= '1';
      busy <= '0';
      done <= '1';
      for subkernel_idx in 0 to 16-1 loop
        if sub_idle(subkernel_idx) = '0' then
          idle <= '0';
        end if;
        if sub_busy(subkernel_idx) = '1' then
          busy <= '1';
        end if;
        if sub_done(subkernel_idx) = '0' then
          done <= '0';
        end if;
      end loop;
      if kcd_reset = '1' then
        idle <= '0';
        busy <= '1';
        done <= '0';
      end if;
    end if;
  end process;

end architecture;
