-- Generated by
--       _______     _             __
--      / _   __|   | |           / /
--     / / | | _  __| |_ __ ___  / /
--    / /  | || |/ _` | '__/ _ \/ /
--   / /   | || | (_| | | |  __/ /
--  /_/    |_||_|\__,_|_|  \____/
--
-- Copyright 2020 Teratide B.V.
-- 
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
-- 
--     http://www.apache.org/licenses/LICENSE-2.0
-- 
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library work;
use work.UtilInt_pkg.all;

entity Kernel is
  generic (
    INDEX_WIDTH : integer := 32;
    TAG_WIDTH   : integer := 1
  );
  port (
    kcd_clk                    : in  std_logic;
    kcd_reset                  : in  std_logic;
    rematch000_in_valid        : in  std_logic;
    rematch000_in_ready        : out std_logic;
    rematch000_in_dvalid       : in  std_logic;
    rematch000_in_last         : in  std_logic;
    rematch000_in_length       : in  std_logic_vector(31 downto 0);
    rematch000_in_count        : in  std_logic_vector(0 downto 0);
    rematch000_in_chars_valid  : in  std_logic;
    rematch000_in_chars_ready  : out std_logic;
    rematch000_in_chars_dvalid : in  std_logic;
    rematch000_in_chars_last   : in  std_logic;
    rematch000_in_chars        : in  std_logic_vector(31 downto 0);
    rematch000_in_chars_count  : in  std_logic_vector(2 downto 0);
    rematch000_in_unl_valid    : in  std_logic;
    rematch000_in_unl_ready    : out std_logic;
    rematch000_in_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch000_in_cmd_valid    : out std_logic;
    rematch000_in_cmd_ready    : in  std_logic;
    rematch000_in_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch000_in_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch000_in_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch001_in_valid        : in  std_logic;
    rematch001_in_ready        : out std_logic;
    rematch001_in_dvalid       : in  std_logic;
    rematch001_in_last         : in  std_logic;
    rematch001_in_length       : in  std_logic_vector(31 downto 0);
    rematch001_in_count        : in  std_logic_vector(0 downto 0);
    rematch001_in_chars_valid  : in  std_logic;
    rematch001_in_chars_ready  : out std_logic;
    rematch001_in_chars_dvalid : in  std_logic;
    rematch001_in_chars_last   : in  std_logic;
    rematch001_in_chars        : in  std_logic_vector(31 downto 0);
    rematch001_in_chars_count  : in  std_logic_vector(2 downto 0);
    rematch001_in_unl_valid    : in  std_logic;
    rematch001_in_unl_ready    : out std_logic;
    rematch001_in_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch001_in_cmd_valid    : out std_logic;
    rematch001_in_cmd_ready    : in  std_logic;
    rematch001_in_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch001_in_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch001_in_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch002_in_valid        : in  std_logic;
    rematch002_in_ready        : out std_logic;
    rematch002_in_dvalid       : in  std_logic;
    rematch002_in_last         : in  std_logic;
    rematch002_in_length       : in  std_logic_vector(31 downto 0);
    rematch002_in_count        : in  std_logic_vector(0 downto 0);
    rematch002_in_chars_valid  : in  std_logic;
    rematch002_in_chars_ready  : out std_logic;
    rematch002_in_chars_dvalid : in  std_logic;
    rematch002_in_chars_last   : in  std_logic;
    rematch002_in_chars        : in  std_logic_vector(31 downto 0);
    rematch002_in_chars_count  : in  std_logic_vector(2 downto 0);
    rematch002_in_unl_valid    : in  std_logic;
    rematch002_in_unl_ready    : out std_logic;
    rematch002_in_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch002_in_cmd_valid    : out std_logic;
    rematch002_in_cmd_ready    : in  std_logic;
    rematch002_in_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch002_in_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch002_in_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch003_in_valid        : in  std_logic;
    rematch003_in_ready        : out std_logic;
    rematch003_in_dvalid       : in  std_logic;
    rematch003_in_last         : in  std_logic;
    rematch003_in_length       : in  std_logic_vector(31 downto 0);
    rematch003_in_count        : in  std_logic_vector(0 downto 0);
    rematch003_in_chars_valid  : in  std_logic;
    rematch003_in_chars_ready  : out std_logic;
    rematch003_in_chars_dvalid : in  std_logic;
    rematch003_in_chars_last   : in  std_logic;
    rematch003_in_chars        : in  std_logic_vector(31 downto 0);
    rematch003_in_chars_count  : in  std_logic_vector(2 downto 0);
    rematch003_in_unl_valid    : in  std_logic;
    rematch003_in_unl_ready    : out std_logic;
    rematch003_in_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch003_in_cmd_valid    : out std_logic;
    rematch003_in_cmd_ready    : in  std_logic;
    rematch003_in_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch003_in_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch003_in_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch004_in_valid        : in  std_logic;
    rematch004_in_ready        : out std_logic;
    rematch004_in_dvalid       : in  std_logic;
    rematch004_in_last         : in  std_logic;
    rematch004_in_length       : in  std_logic_vector(31 downto 0);
    rematch004_in_count        : in  std_logic_vector(0 downto 0);
    rematch004_in_chars_valid  : in  std_logic;
    rematch004_in_chars_ready  : out std_logic;
    rematch004_in_chars_dvalid : in  std_logic;
    rematch004_in_chars_last   : in  std_logic;
    rematch004_in_chars        : in  std_logic_vector(31 downto 0);
    rematch004_in_chars_count  : in  std_logic_vector(2 downto 0);
    rematch004_in_unl_valid    : in  std_logic;
    rematch004_in_unl_ready    : out std_logic;
    rematch004_in_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch004_in_cmd_valid    : out std_logic;
    rematch004_in_cmd_ready    : in  std_logic;
    rematch004_in_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch004_in_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch004_in_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch005_in_valid        : in  std_logic;
    rematch005_in_ready        : out std_logic;
    rematch005_in_dvalid       : in  std_logic;
    rematch005_in_last         : in  std_logic;
    rematch005_in_length       : in  std_logic_vector(31 downto 0);
    rematch005_in_count        : in  std_logic_vector(0 downto 0);
    rematch005_in_chars_valid  : in  std_logic;
    rematch005_in_chars_ready  : out std_logic;
    rematch005_in_chars_dvalid : in  std_logic;
    rematch005_in_chars_last   : in  std_logic;
    rematch005_in_chars        : in  std_logic_vector(31 downto 0);
    rematch005_in_chars_count  : in  std_logic_vector(2 downto 0);
    rematch005_in_unl_valid    : in  std_logic;
    rematch005_in_unl_ready    : out std_logic;
    rematch005_in_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch005_in_cmd_valid    : out std_logic;
    rematch005_in_cmd_ready    : in  std_logic;
    rematch005_in_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch005_in_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch005_in_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch006_in_valid        : in  std_logic;
    rematch006_in_ready        : out std_logic;
    rematch006_in_dvalid       : in  std_logic;
    rematch006_in_last         : in  std_logic;
    rematch006_in_length       : in  std_logic_vector(31 downto 0);
    rematch006_in_count        : in  std_logic_vector(0 downto 0);
    rematch006_in_chars_valid  : in  std_logic;
    rematch006_in_chars_ready  : out std_logic;
    rematch006_in_chars_dvalid : in  std_logic;
    rematch006_in_chars_last   : in  std_logic;
    rematch006_in_chars        : in  std_logic_vector(31 downto 0);
    rematch006_in_chars_count  : in  std_logic_vector(2 downto 0);
    rematch006_in_unl_valid    : in  std_logic;
    rematch006_in_unl_ready    : out std_logic;
    rematch006_in_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch006_in_cmd_valid    : out std_logic;
    rematch006_in_cmd_ready    : in  std_logic;
    rematch006_in_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch006_in_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch006_in_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch007_in_valid        : in  std_logic;
    rematch007_in_ready        : out std_logic;
    rematch007_in_dvalid       : in  std_logic;
    rematch007_in_last         : in  std_logic;
    rematch007_in_length       : in  std_logic_vector(31 downto 0);
    rematch007_in_count        : in  std_logic_vector(0 downto 0);
    rematch007_in_chars_valid  : in  std_logic;
    rematch007_in_chars_ready  : out std_logic;
    rematch007_in_chars_dvalid : in  std_logic;
    rematch007_in_chars_last   : in  std_logic;
    rematch007_in_chars        : in  std_logic_vector(31 downto 0);
    rematch007_in_chars_count  : in  std_logic_vector(2 downto 0);
    rematch007_in_unl_valid    : in  std_logic;
    rematch007_in_unl_ready    : out std_logic;
    rematch007_in_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch007_in_cmd_valid    : out std_logic;
    rematch007_in_cmd_ready    : in  std_logic;
    rematch007_in_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch007_in_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch007_in_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch008_in_valid        : in  std_logic;
    rematch008_in_ready        : out std_logic;
    rematch008_in_dvalid       : in  std_logic;
    rematch008_in_last         : in  std_logic;
    rematch008_in_length       : in  std_logic_vector(31 downto 0);
    rematch008_in_count        : in  std_logic_vector(0 downto 0);
    rematch008_in_chars_valid  : in  std_logic;
    rematch008_in_chars_ready  : out std_logic;
    rematch008_in_chars_dvalid : in  std_logic;
    rematch008_in_chars_last   : in  std_logic;
    rematch008_in_chars        : in  std_logic_vector(31 downto 0);
    rematch008_in_chars_count  : in  std_logic_vector(2 downto 0);
    rematch008_in_unl_valid    : in  std_logic;
    rematch008_in_unl_ready    : out std_logic;
    rematch008_in_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch008_in_cmd_valid    : out std_logic;
    rematch008_in_cmd_ready    : in  std_logic;
    rematch008_in_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch008_in_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch008_in_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch009_in_valid        : in  std_logic;
    rematch009_in_ready        : out std_logic;
    rematch009_in_dvalid       : in  std_logic;
    rematch009_in_last         : in  std_logic;
    rematch009_in_length       : in  std_logic_vector(31 downto 0);
    rematch009_in_count        : in  std_logic_vector(0 downto 0);
    rematch009_in_chars_valid  : in  std_logic;
    rematch009_in_chars_ready  : out std_logic;
    rematch009_in_chars_dvalid : in  std_logic;
    rematch009_in_chars_last   : in  std_logic;
    rematch009_in_chars        : in  std_logic_vector(31 downto 0);
    rematch009_in_chars_count  : in  std_logic_vector(2 downto 0);
    rematch009_in_unl_valid    : in  std_logic;
    rematch009_in_unl_ready    : out std_logic;
    rematch009_in_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch009_in_cmd_valid    : out std_logic;
    rematch009_in_cmd_ready    : in  std_logic;
    rematch009_in_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch009_in_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch009_in_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch010_in_valid        : in  std_logic;
    rematch010_in_ready        : out std_logic;
    rematch010_in_dvalid       : in  std_logic;
    rematch010_in_last         : in  std_logic;
    rematch010_in_length       : in  std_logic_vector(31 downto 0);
    rematch010_in_count        : in  std_logic_vector(0 downto 0);
    rematch010_in_chars_valid  : in  std_logic;
    rematch010_in_chars_ready  : out std_logic;
    rematch010_in_chars_dvalid : in  std_logic;
    rematch010_in_chars_last   : in  std_logic;
    rematch010_in_chars        : in  std_logic_vector(31 downto 0);
    rematch010_in_chars_count  : in  std_logic_vector(2 downto 0);
    rematch010_in_unl_valid    : in  std_logic;
    rematch010_in_unl_ready    : out std_logic;
    rematch010_in_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch010_in_cmd_valid    : out std_logic;
    rematch010_in_cmd_ready    : in  std_logic;
    rematch010_in_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch010_in_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch010_in_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch011_in_valid        : in  std_logic;
    rematch011_in_ready        : out std_logic;
    rematch011_in_dvalid       : in  std_logic;
    rematch011_in_last         : in  std_logic;
    rematch011_in_length       : in  std_logic_vector(31 downto 0);
    rematch011_in_count        : in  std_logic_vector(0 downto 0);
    rematch011_in_chars_valid  : in  std_logic;
    rematch011_in_chars_ready  : out std_logic;
    rematch011_in_chars_dvalid : in  std_logic;
    rematch011_in_chars_last   : in  std_logic;
    rematch011_in_chars        : in  std_logic_vector(31 downto 0);
    rematch011_in_chars_count  : in  std_logic_vector(2 downto 0);
    rematch011_in_unl_valid    : in  std_logic;
    rematch011_in_unl_ready    : out std_logic;
    rematch011_in_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch011_in_cmd_valid    : out std_logic;
    rematch011_in_cmd_ready    : in  std_logic;
    rematch011_in_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch011_in_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch011_in_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch012_in_valid        : in  std_logic;
    rematch012_in_ready        : out std_logic;
    rematch012_in_dvalid       : in  std_logic;
    rematch012_in_last         : in  std_logic;
    rematch012_in_length       : in  std_logic_vector(31 downto 0);
    rematch012_in_count        : in  std_logic_vector(0 downto 0);
    rematch012_in_chars_valid  : in  std_logic;
    rematch012_in_chars_ready  : out std_logic;
    rematch012_in_chars_dvalid : in  std_logic;
    rematch012_in_chars_last   : in  std_logic;
    rematch012_in_chars        : in  std_logic_vector(31 downto 0);
    rematch012_in_chars_count  : in  std_logic_vector(2 downto 0);
    rematch012_in_unl_valid    : in  std_logic;
    rematch012_in_unl_ready    : out std_logic;
    rematch012_in_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch012_in_cmd_valid    : out std_logic;
    rematch012_in_cmd_ready    : in  std_logic;
    rematch012_in_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch012_in_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch012_in_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch013_in_valid        : in  std_logic;
    rematch013_in_ready        : out std_logic;
    rematch013_in_dvalid       : in  std_logic;
    rematch013_in_last         : in  std_logic;
    rematch013_in_length       : in  std_logic_vector(31 downto 0);
    rematch013_in_count        : in  std_logic_vector(0 downto 0);
    rematch013_in_chars_valid  : in  std_logic;
    rematch013_in_chars_ready  : out std_logic;
    rematch013_in_chars_dvalid : in  std_logic;
    rematch013_in_chars_last   : in  std_logic;
    rematch013_in_chars        : in  std_logic_vector(31 downto 0);
    rematch013_in_chars_count  : in  std_logic_vector(2 downto 0);
    rematch013_in_unl_valid    : in  std_logic;
    rematch013_in_unl_ready    : out std_logic;
    rematch013_in_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch013_in_cmd_valid    : out std_logic;
    rematch013_in_cmd_ready    : in  std_logic;
    rematch013_in_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch013_in_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch013_in_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch014_in_valid        : in  std_logic;
    rematch014_in_ready        : out std_logic;
    rematch014_in_dvalid       : in  std_logic;
    rematch014_in_last         : in  std_logic;
    rematch014_in_length       : in  std_logic_vector(31 downto 0);
    rematch014_in_count        : in  std_logic_vector(0 downto 0);
    rematch014_in_chars_valid  : in  std_logic;
    rematch014_in_chars_ready  : out std_logic;
    rematch014_in_chars_dvalid : in  std_logic;
    rematch014_in_chars_last   : in  std_logic;
    rematch014_in_chars        : in  std_logic_vector(31 downto 0);
    rematch014_in_chars_count  : in  std_logic_vector(2 downto 0);
    rematch014_in_unl_valid    : in  std_logic;
    rematch014_in_unl_ready    : out std_logic;
    rematch014_in_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch014_in_cmd_valid    : out std_logic;
    rematch014_in_cmd_ready    : in  std_logic;
    rematch014_in_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch014_in_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch014_in_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch015_in_valid        : in  std_logic;
    rematch015_in_ready        : out std_logic;
    rematch015_in_dvalid       : in  std_logic;
    rematch015_in_last         : in  std_logic;
    rematch015_in_length       : in  std_logic_vector(31 downto 0);
    rematch015_in_count        : in  std_logic_vector(0 downto 0);
    rematch015_in_chars_valid  : in  std_logic;
    rematch015_in_chars_ready  : out std_logic;
    rematch015_in_chars_dvalid : in  std_logic;
    rematch015_in_chars_last   : in  std_logic;
    rematch015_in_chars        : in  std_logic_vector(31 downto 0);
    rematch015_in_chars_count  : in  std_logic_vector(2 downto 0);
    rematch015_in_unl_valid    : in  std_logic;
    rematch015_in_unl_ready    : out std_logic;
    rematch015_in_unl_tag      : in  std_logic_vector(TAG_WIDTH-1 downto 0);
    rematch015_in_cmd_valid    : out std_logic;
    rematch015_in_cmd_ready    : in  std_logic;
    rematch015_in_cmd_firstIdx : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch015_in_cmd_lastIdx  : out std_logic_vector(INDEX_WIDTH-1 downto 0);
    rematch015_in_cmd_tag      : out std_logic_vector(TAG_WIDTH-1 downto 0);
    start                      : in  std_logic;
    stop                       : in  std_logic;
    reset                      : in  std_logic;
    idle                       : out std_logic;
    busy                       : out std_logic;
    done                       : out std_logic;
    result                     : out std_logic_vector(63 downto 0);
    rematch000_firstidx        : in  std_logic_vector(31 downto 0);
    rematch000_lastidx         : in  std_logic_vector(31 downto 0);
    rematch001_firstidx        : in  std_logic_vector(31 downto 0);
    rematch001_lastidx         : in  std_logic_vector(31 downto 0);
    rematch002_firstidx        : in  std_logic_vector(31 downto 0);
    rematch002_lastidx         : in  std_logic_vector(31 downto 0);
    rematch003_firstidx        : in  std_logic_vector(31 downto 0);
    rematch003_lastidx         : in  std_logic_vector(31 downto 0);
    rematch004_firstidx        : in  std_logic_vector(31 downto 0);
    rematch004_lastidx         : in  std_logic_vector(31 downto 0);
    rematch005_firstidx        : in  std_logic_vector(31 downto 0);
    rematch005_lastidx         : in  std_logic_vector(31 downto 0);
    rematch006_firstidx        : in  std_logic_vector(31 downto 0);
    rematch006_lastidx         : in  std_logic_vector(31 downto 0);
    rematch007_firstidx        : in  std_logic_vector(31 downto 0);
    rematch007_lastidx         : in  std_logic_vector(31 downto 0);
    rematch008_firstidx        : in  std_logic_vector(31 downto 0);
    rematch008_lastidx         : in  std_logic_vector(31 downto 0);
    rematch009_firstidx        : in  std_logic_vector(31 downto 0);
    rematch009_lastidx         : in  std_logic_vector(31 downto 0);
    rematch010_firstidx        : in  std_logic_vector(31 downto 0);
    rematch010_lastidx         : in  std_logic_vector(31 downto 0);
    rematch011_firstidx        : in  std_logic_vector(31 downto 0);
    rematch011_lastidx         : in  std_logic_vector(31 downto 0);
    rematch012_firstidx        : in  std_logic_vector(31 downto 0);
    rematch012_lastidx         : in  std_logic_vector(31 downto 0);
    rematch013_firstidx        : in  std_logic_vector(31 downto 0);
    rematch013_lastidx         : in  std_logic_vector(31 downto 0);
    rematch014_firstidx        : in  std_logic_vector(31 downto 0);
    rematch014_lastidx         : in  std_logic_vector(31 downto 0);
    rematch015_firstidx        : in  std_logic_vector(31 downto 0);
    rematch015_lastidx         : in  std_logic_vector(31 downto 0);
    count_re_bird              : out std_logic_vector(31 downto 0);
    count_re_bunny             : out std_logic_vector(31 downto 0);
    count_re_cat               : out std_logic_vector(31 downto 0);
    count_re_dog               : out std_logic_vector(31 downto 0);
    count_re_ferret            : out std_logic_vector(31 downto 0);
    count_re_fish              : out std_logic_vector(31 downto 0);
    count_re_gerbil            : out std_logic_vector(31 downto 0);
    count_re_hamster           : out std_logic_vector(31 downto 0);
    count_re_horse             : out std_logic_vector(31 downto 0);
    count_re_kitten            : out std_logic_vector(31 downto 0);
    count_re_lizard            : out std_logic_vector(31 downto 0);
    count_re_mouse             : out std_logic_vector(31 downto 0);
    count_re_puppy             : out std_logic_vector(31 downto 0);
    count_re_rabbit            : out std_logic_vector(31 downto 0);
    count_re_rat               : out std_logic_vector(31 downto 0);
    count_re_turtle            : out std_logic_vector(31 downto 0);
    count_errors               : out std_logic_vector(31 downto 0)
  );
end entity;

architecture Implementation of Kernel is

  signal sub_idle   : std_logic_vector(16-1 downto 0);
  signal sub_busy   : std_logic_vector(16-1 downto 0);
  signal sub_done   : std_logic_vector(16-1 downto 0);

  type match_array is array (natural range <>) of std_logic_vector(16-1 downto 0);
  signal sub_match  : match_array(16-1 downto 0);
  signal sub_error  : std_logic_vector(16-1 downto 0);

  type increment_array is array (natural range <>) of std_logic_vector(log2ceil(16+1)-1 downto 0);
  signal increments : increment_array(16 downto 0);

  type counter_array is array (natural range <>) of std_logic_vector(31 downto 0);
  signal counters   : counter_array(16 downto 0);

begin

  rematch000: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 16,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,
      in_valid                 => rematch000_in_valid,
      in_ready                 => rematch000_in_ready,
      in_dvalid                => rematch000_in_dvalid,
      in_last                  => rematch000_in_last,
      in_length                => rematch000_in_length,
      in_count                 => rematch000_in_count,
      in_chars_valid           => rematch000_in_chars_valid,
      in_chars_ready           => rematch000_in_chars_ready,
      in_chars_dvalid          => rematch000_in_chars_dvalid,
      in_chars_last            => rematch000_in_chars_last,
      in_chars                 => rematch000_in_chars,
      in_chars_count           => rematch000_in_chars_count,
      in_unl_valid             => rematch000_in_unl_valid,
      in_unl_ready             => rematch000_in_unl_ready,
      in_unl_tag               => rematch000_in_unl_tag,
      in_cmd_valid             => rematch000_in_cmd_valid,
      in_cmd_ready             => rematch000_in_cmd_ready,
      in_cmd_firstIdx          => rematch000_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch000_in_cmd_lastIdx,
      in_cmd_tag               => rematch000_in_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(0),
      mmio_busy                => sub_busy(0),
      mmio_done                => sub_done(0),
      mmio_firstidx            => rematch000_firstidx,
      mmio_lastidx             => rematch000_lastidx,

      -- Counter increment outputs.
      out_match                => sub_match(0),
      out_error                => sub_error(0)

    );

  rematch001: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 16,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,
      in_valid                 => rematch001_in_valid,
      in_ready                 => rematch001_in_ready,
      in_dvalid                => rematch001_in_dvalid,
      in_last                  => rematch001_in_last,
      in_length                => rematch001_in_length,
      in_count                 => rematch001_in_count,
      in_chars_valid           => rematch001_in_chars_valid,
      in_chars_ready           => rematch001_in_chars_ready,
      in_chars_dvalid          => rematch001_in_chars_dvalid,
      in_chars_last            => rematch001_in_chars_last,
      in_chars                 => rematch001_in_chars,
      in_chars_count           => rematch001_in_chars_count,
      in_unl_valid             => rematch001_in_unl_valid,
      in_unl_ready             => rematch001_in_unl_ready,
      in_unl_tag               => rematch001_in_unl_tag,
      in_cmd_valid             => rematch001_in_cmd_valid,
      in_cmd_ready             => rematch001_in_cmd_ready,
      in_cmd_firstIdx          => rematch001_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch001_in_cmd_lastIdx,
      in_cmd_tag               => rematch001_in_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(1),
      mmio_busy                => sub_busy(1),
      mmio_done                => sub_done(1),
      mmio_firstidx            => rematch001_firstidx,
      mmio_lastidx             => rematch001_lastidx,

      -- Counter increment outputs.
      out_match                => sub_match(1),
      out_error                => sub_error(1)

    );

  rematch002: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 16,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,
      in_valid                 => rematch002_in_valid,
      in_ready                 => rematch002_in_ready,
      in_dvalid                => rematch002_in_dvalid,
      in_last                  => rematch002_in_last,
      in_length                => rematch002_in_length,
      in_count                 => rematch002_in_count,
      in_chars_valid           => rematch002_in_chars_valid,
      in_chars_ready           => rematch002_in_chars_ready,
      in_chars_dvalid          => rematch002_in_chars_dvalid,
      in_chars_last            => rematch002_in_chars_last,
      in_chars                 => rematch002_in_chars,
      in_chars_count           => rematch002_in_chars_count,
      in_unl_valid             => rematch002_in_unl_valid,
      in_unl_ready             => rematch002_in_unl_ready,
      in_unl_tag               => rematch002_in_unl_tag,
      in_cmd_valid             => rematch002_in_cmd_valid,
      in_cmd_ready             => rematch002_in_cmd_ready,
      in_cmd_firstIdx          => rematch002_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch002_in_cmd_lastIdx,
      in_cmd_tag               => rematch002_in_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(2),
      mmio_busy                => sub_busy(2),
      mmio_done                => sub_done(2),
      mmio_firstidx            => rematch002_firstidx,
      mmio_lastidx             => rematch002_lastidx,

      -- Counter increment outputs.
      out_match                => sub_match(2),
      out_error                => sub_error(2)

    );

  rematch003: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 16,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,
      in_valid                 => rematch003_in_valid,
      in_ready                 => rematch003_in_ready,
      in_dvalid                => rematch003_in_dvalid,
      in_last                  => rematch003_in_last,
      in_length                => rematch003_in_length,
      in_count                 => rematch003_in_count,
      in_chars_valid           => rematch003_in_chars_valid,
      in_chars_ready           => rematch003_in_chars_ready,
      in_chars_dvalid          => rematch003_in_chars_dvalid,
      in_chars_last            => rematch003_in_chars_last,
      in_chars                 => rematch003_in_chars,
      in_chars_count           => rematch003_in_chars_count,
      in_unl_valid             => rematch003_in_unl_valid,
      in_unl_ready             => rematch003_in_unl_ready,
      in_unl_tag               => rematch003_in_unl_tag,
      in_cmd_valid             => rematch003_in_cmd_valid,
      in_cmd_ready             => rematch003_in_cmd_ready,
      in_cmd_firstIdx          => rematch003_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch003_in_cmd_lastIdx,
      in_cmd_tag               => rematch003_in_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(3),
      mmio_busy                => sub_busy(3),
      mmio_done                => sub_done(3),
      mmio_firstidx            => rematch003_firstidx,
      mmio_lastidx             => rematch003_lastidx,

      -- Counter increment outputs.
      out_match                => sub_match(3),
      out_error                => sub_error(3)

    );

  rematch004: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 16,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,
      in_valid                 => rematch004_in_valid,
      in_ready                 => rematch004_in_ready,
      in_dvalid                => rematch004_in_dvalid,
      in_last                  => rematch004_in_last,
      in_length                => rematch004_in_length,
      in_count                 => rematch004_in_count,
      in_chars_valid           => rematch004_in_chars_valid,
      in_chars_ready           => rematch004_in_chars_ready,
      in_chars_dvalid          => rematch004_in_chars_dvalid,
      in_chars_last            => rematch004_in_chars_last,
      in_chars                 => rematch004_in_chars,
      in_chars_count           => rematch004_in_chars_count,
      in_unl_valid             => rematch004_in_unl_valid,
      in_unl_ready             => rematch004_in_unl_ready,
      in_unl_tag               => rematch004_in_unl_tag,
      in_cmd_valid             => rematch004_in_cmd_valid,
      in_cmd_ready             => rematch004_in_cmd_ready,
      in_cmd_firstIdx          => rematch004_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch004_in_cmd_lastIdx,
      in_cmd_tag               => rematch004_in_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(4),
      mmio_busy                => sub_busy(4),
      mmio_done                => sub_done(4),
      mmio_firstidx            => rematch004_firstidx,
      mmio_lastidx             => rematch004_lastidx,

      -- Counter increment outputs.
      out_match                => sub_match(4),
      out_error                => sub_error(4)

    );

  rematch005: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 16,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,
      in_valid                 => rematch005_in_valid,
      in_ready                 => rematch005_in_ready,
      in_dvalid                => rematch005_in_dvalid,
      in_last                  => rematch005_in_last,
      in_length                => rematch005_in_length,
      in_count                 => rematch005_in_count,
      in_chars_valid           => rematch005_in_chars_valid,
      in_chars_ready           => rematch005_in_chars_ready,
      in_chars_dvalid          => rematch005_in_chars_dvalid,
      in_chars_last            => rematch005_in_chars_last,
      in_chars                 => rematch005_in_chars,
      in_chars_count           => rematch005_in_chars_count,
      in_unl_valid             => rematch005_in_unl_valid,
      in_unl_ready             => rematch005_in_unl_ready,
      in_unl_tag               => rematch005_in_unl_tag,
      in_cmd_valid             => rematch005_in_cmd_valid,
      in_cmd_ready             => rematch005_in_cmd_ready,
      in_cmd_firstIdx          => rematch005_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch005_in_cmd_lastIdx,
      in_cmd_tag               => rematch005_in_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(5),
      mmio_busy                => sub_busy(5),
      mmio_done                => sub_done(5),
      mmio_firstidx            => rematch005_firstidx,
      mmio_lastidx             => rematch005_lastidx,

      -- Counter increment outputs.
      out_match                => sub_match(5),
      out_error                => sub_error(5)

    );

  rematch006: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 16,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,
      in_valid                 => rematch006_in_valid,
      in_ready                 => rematch006_in_ready,
      in_dvalid                => rematch006_in_dvalid,
      in_last                  => rematch006_in_last,
      in_length                => rematch006_in_length,
      in_count                 => rematch006_in_count,
      in_chars_valid           => rematch006_in_chars_valid,
      in_chars_ready           => rematch006_in_chars_ready,
      in_chars_dvalid          => rematch006_in_chars_dvalid,
      in_chars_last            => rematch006_in_chars_last,
      in_chars                 => rematch006_in_chars,
      in_chars_count           => rematch006_in_chars_count,
      in_unl_valid             => rematch006_in_unl_valid,
      in_unl_ready             => rematch006_in_unl_ready,
      in_unl_tag               => rematch006_in_unl_tag,
      in_cmd_valid             => rematch006_in_cmd_valid,
      in_cmd_ready             => rematch006_in_cmd_ready,
      in_cmd_firstIdx          => rematch006_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch006_in_cmd_lastIdx,
      in_cmd_tag               => rematch006_in_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(6),
      mmio_busy                => sub_busy(6),
      mmio_done                => sub_done(6),
      mmio_firstidx            => rematch006_firstidx,
      mmio_lastidx             => rematch006_lastidx,

      -- Counter increment outputs.
      out_match                => sub_match(6),
      out_error                => sub_error(6)

    );

  rematch007: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 16,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,
      in_valid                 => rematch007_in_valid,
      in_ready                 => rematch007_in_ready,
      in_dvalid                => rematch007_in_dvalid,
      in_last                  => rematch007_in_last,
      in_length                => rematch007_in_length,
      in_count                 => rematch007_in_count,
      in_chars_valid           => rematch007_in_chars_valid,
      in_chars_ready           => rematch007_in_chars_ready,
      in_chars_dvalid          => rematch007_in_chars_dvalid,
      in_chars_last            => rematch007_in_chars_last,
      in_chars                 => rematch007_in_chars,
      in_chars_count           => rematch007_in_chars_count,
      in_unl_valid             => rematch007_in_unl_valid,
      in_unl_ready             => rematch007_in_unl_ready,
      in_unl_tag               => rematch007_in_unl_tag,
      in_cmd_valid             => rematch007_in_cmd_valid,
      in_cmd_ready             => rematch007_in_cmd_ready,
      in_cmd_firstIdx          => rematch007_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch007_in_cmd_lastIdx,
      in_cmd_tag               => rematch007_in_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(7),
      mmio_busy                => sub_busy(7),
      mmio_done                => sub_done(7),
      mmio_firstidx            => rematch007_firstidx,
      mmio_lastidx             => rematch007_lastidx,

      -- Counter increment outputs.
      out_match                => sub_match(7),
      out_error                => sub_error(7)

    );

  rematch008: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 16,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,
      in_valid                 => rematch008_in_valid,
      in_ready                 => rematch008_in_ready,
      in_dvalid                => rematch008_in_dvalid,
      in_last                  => rematch008_in_last,
      in_length                => rematch008_in_length,
      in_count                 => rematch008_in_count,
      in_chars_valid           => rematch008_in_chars_valid,
      in_chars_ready           => rematch008_in_chars_ready,
      in_chars_dvalid          => rematch008_in_chars_dvalid,
      in_chars_last            => rematch008_in_chars_last,
      in_chars                 => rematch008_in_chars,
      in_chars_count           => rematch008_in_chars_count,
      in_unl_valid             => rematch008_in_unl_valid,
      in_unl_ready             => rematch008_in_unl_ready,
      in_unl_tag               => rematch008_in_unl_tag,
      in_cmd_valid             => rematch008_in_cmd_valid,
      in_cmd_ready             => rematch008_in_cmd_ready,
      in_cmd_firstIdx          => rematch008_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch008_in_cmd_lastIdx,
      in_cmd_tag               => rematch008_in_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(8),
      mmio_busy                => sub_busy(8),
      mmio_done                => sub_done(8),
      mmio_firstidx            => rematch008_firstidx,
      mmio_lastidx             => rematch008_lastidx,

      -- Counter increment outputs.
      out_match                => sub_match(8),
      out_error                => sub_error(8)

    );

  rematch009: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 16,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,
      in_valid                 => rematch009_in_valid,
      in_ready                 => rematch009_in_ready,
      in_dvalid                => rematch009_in_dvalid,
      in_last                  => rematch009_in_last,
      in_length                => rematch009_in_length,
      in_count                 => rematch009_in_count,
      in_chars_valid           => rematch009_in_chars_valid,
      in_chars_ready           => rematch009_in_chars_ready,
      in_chars_dvalid          => rematch009_in_chars_dvalid,
      in_chars_last            => rematch009_in_chars_last,
      in_chars                 => rematch009_in_chars,
      in_chars_count           => rematch009_in_chars_count,
      in_unl_valid             => rematch009_in_unl_valid,
      in_unl_ready             => rematch009_in_unl_ready,
      in_unl_tag               => rematch009_in_unl_tag,
      in_cmd_valid             => rematch009_in_cmd_valid,
      in_cmd_ready             => rematch009_in_cmd_ready,
      in_cmd_firstIdx          => rematch009_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch009_in_cmd_lastIdx,
      in_cmd_tag               => rematch009_in_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(9),
      mmio_busy                => sub_busy(9),
      mmio_done                => sub_done(9),
      mmio_firstidx            => rematch009_firstidx,
      mmio_lastidx             => rematch009_lastidx,

      -- Counter increment outputs.
      out_match                => sub_match(9),
      out_error                => sub_error(9)

    );

  rematch010: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 16,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,
      in_valid                 => rematch010_in_valid,
      in_ready                 => rematch010_in_ready,
      in_dvalid                => rematch010_in_dvalid,
      in_last                  => rematch010_in_last,
      in_length                => rematch010_in_length,
      in_count                 => rematch010_in_count,
      in_chars_valid           => rematch010_in_chars_valid,
      in_chars_ready           => rematch010_in_chars_ready,
      in_chars_dvalid          => rematch010_in_chars_dvalid,
      in_chars_last            => rematch010_in_chars_last,
      in_chars                 => rematch010_in_chars,
      in_chars_count           => rematch010_in_chars_count,
      in_unl_valid             => rematch010_in_unl_valid,
      in_unl_ready             => rematch010_in_unl_ready,
      in_unl_tag               => rematch010_in_unl_tag,
      in_cmd_valid             => rematch010_in_cmd_valid,
      in_cmd_ready             => rematch010_in_cmd_ready,
      in_cmd_firstIdx          => rematch010_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch010_in_cmd_lastIdx,
      in_cmd_tag               => rematch010_in_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(10),
      mmio_busy                => sub_busy(10),
      mmio_done                => sub_done(10),
      mmio_firstidx            => rematch010_firstidx,
      mmio_lastidx             => rematch010_lastidx,

      -- Counter increment outputs.
      out_match                => sub_match(10),
      out_error                => sub_error(10)

    );

  rematch011: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 16,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,
      in_valid                 => rematch011_in_valid,
      in_ready                 => rematch011_in_ready,
      in_dvalid                => rematch011_in_dvalid,
      in_last                  => rematch011_in_last,
      in_length                => rematch011_in_length,
      in_count                 => rematch011_in_count,
      in_chars_valid           => rematch011_in_chars_valid,
      in_chars_ready           => rematch011_in_chars_ready,
      in_chars_dvalid          => rematch011_in_chars_dvalid,
      in_chars_last            => rematch011_in_chars_last,
      in_chars                 => rematch011_in_chars,
      in_chars_count           => rematch011_in_chars_count,
      in_unl_valid             => rematch011_in_unl_valid,
      in_unl_ready             => rematch011_in_unl_ready,
      in_unl_tag               => rematch011_in_unl_tag,
      in_cmd_valid             => rematch011_in_cmd_valid,
      in_cmd_ready             => rematch011_in_cmd_ready,
      in_cmd_firstIdx          => rematch011_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch011_in_cmd_lastIdx,
      in_cmd_tag               => rematch011_in_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(11),
      mmio_busy                => sub_busy(11),
      mmio_done                => sub_done(11),
      mmio_firstidx            => rematch011_firstidx,
      mmio_lastidx             => rematch011_lastidx,

      -- Counter increment outputs.
      out_match                => sub_match(11),
      out_error                => sub_error(11)

    );

  rematch012: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 16,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,
      in_valid                 => rematch012_in_valid,
      in_ready                 => rematch012_in_ready,
      in_dvalid                => rematch012_in_dvalid,
      in_last                  => rematch012_in_last,
      in_length                => rematch012_in_length,
      in_count                 => rematch012_in_count,
      in_chars_valid           => rematch012_in_chars_valid,
      in_chars_ready           => rematch012_in_chars_ready,
      in_chars_dvalid          => rematch012_in_chars_dvalid,
      in_chars_last            => rematch012_in_chars_last,
      in_chars                 => rematch012_in_chars,
      in_chars_count           => rematch012_in_chars_count,
      in_unl_valid             => rematch012_in_unl_valid,
      in_unl_ready             => rematch012_in_unl_ready,
      in_unl_tag               => rematch012_in_unl_tag,
      in_cmd_valid             => rematch012_in_cmd_valid,
      in_cmd_ready             => rematch012_in_cmd_ready,
      in_cmd_firstIdx          => rematch012_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch012_in_cmd_lastIdx,
      in_cmd_tag               => rematch012_in_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(12),
      mmio_busy                => sub_busy(12),
      mmio_done                => sub_done(12),
      mmio_firstidx            => rematch012_firstidx,
      mmio_lastidx             => rematch012_lastidx,

      -- Counter increment outputs.
      out_match                => sub_match(12),
      out_error                => sub_error(12)

    );

  rematch013: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 16,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,
      in_valid                 => rematch013_in_valid,
      in_ready                 => rematch013_in_ready,
      in_dvalid                => rematch013_in_dvalid,
      in_last                  => rematch013_in_last,
      in_length                => rematch013_in_length,
      in_count                 => rematch013_in_count,
      in_chars_valid           => rematch013_in_chars_valid,
      in_chars_ready           => rematch013_in_chars_ready,
      in_chars_dvalid          => rematch013_in_chars_dvalid,
      in_chars_last            => rematch013_in_chars_last,
      in_chars                 => rematch013_in_chars,
      in_chars_count           => rematch013_in_chars_count,
      in_unl_valid             => rematch013_in_unl_valid,
      in_unl_ready             => rematch013_in_unl_ready,
      in_unl_tag               => rematch013_in_unl_tag,
      in_cmd_valid             => rematch013_in_cmd_valid,
      in_cmd_ready             => rematch013_in_cmd_ready,
      in_cmd_firstIdx          => rematch013_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch013_in_cmd_lastIdx,
      in_cmd_tag               => rematch013_in_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(13),
      mmio_busy                => sub_busy(13),
      mmio_done                => sub_done(13),
      mmio_firstidx            => rematch013_firstidx,
      mmio_lastidx             => rematch013_lastidx,

      -- Counter increment outputs.
      out_match                => sub_match(13),
      out_error                => sub_error(13)

    );

  rematch014: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 16,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,
      in_valid                 => rematch014_in_valid,
      in_ready                 => rematch014_in_ready,
      in_dvalid                => rematch014_in_dvalid,
      in_last                  => rematch014_in_last,
      in_length                => rematch014_in_length,
      in_count                 => rematch014_in_count,
      in_chars_valid           => rematch014_in_chars_valid,
      in_chars_ready           => rematch014_in_chars_ready,
      in_chars_dvalid          => rematch014_in_chars_dvalid,
      in_chars_last            => rematch014_in_chars_last,
      in_chars                 => rematch014_in_chars,
      in_chars_count           => rematch014_in_chars_count,
      in_unl_valid             => rematch014_in_unl_valid,
      in_unl_ready             => rematch014_in_unl_ready,
      in_unl_tag               => rematch014_in_unl_tag,
      in_cmd_valid             => rematch014_in_cmd_valid,
      in_cmd_ready             => rematch014_in_cmd_ready,
      in_cmd_firstIdx          => rematch014_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch014_in_cmd_lastIdx,
      in_cmd_tag               => rematch014_in_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(14),
      mmio_busy                => sub_busy(14),
      mmio_done                => sub_done(14),
      mmio_firstidx            => rematch014_firstidx,
      mmio_lastidx             => rematch014_lastidx,

      -- Counter increment outputs.
      out_match                => sub_match(14),
      out_error                => sub_error(14)

    );

  rematch015: entity work.SubKernel
    generic map (
      NUM_EPC                  => 4,
      NUM_REGEX                => 16,
      INDEX_WIDTH              => INDEX_WIDTH,
      TAG_WIDTH                => TAG_WIDTH
    )
    port map (
      kcd_clk                  => kcd_clk,
      kcd_reset                => kcd_reset,
      in_valid                 => rematch015_in_valid,
      in_ready                 => rematch015_in_ready,
      in_dvalid                => rematch015_in_dvalid,
      in_last                  => rematch015_in_last,
      in_length                => rematch015_in_length,
      in_count                 => rematch015_in_count,
      in_chars_valid           => rematch015_in_chars_valid,
      in_chars_ready           => rematch015_in_chars_ready,
      in_chars_dvalid          => rematch015_in_chars_dvalid,
      in_chars_last            => rematch015_in_chars_last,
      in_chars                 => rematch015_in_chars,
      in_chars_count           => rematch015_in_chars_count,
      in_unl_valid             => rematch015_in_unl_valid,
      in_unl_ready             => rematch015_in_unl_ready,
      in_unl_tag               => rematch015_in_unl_tag,
      in_cmd_valid             => rematch015_in_cmd_valid,
      in_cmd_ready             => rematch015_in_cmd_ready,
      in_cmd_firstIdx          => rematch015_in_cmd_firstIdx,
      in_cmd_lastIdx           => rematch015_in_cmd_lastIdx,
      in_cmd_tag               => rematch015_in_cmd_tag,

      -- MMIO control interface.
      mmio_start               => start,
      mmio_stop                => stop,
      mmio_reset               => reset,
      mmio_idle                => sub_idle(15),
      mmio_busy                => sub_busy(15),
      mmio_done                => sub_done(15),
      mmio_firstidx            => rematch015_firstidx,
      mmio_lastidx             => rematch015_lastidx,

      -- Counter increment outputs.
      out_match                => sub_match(15),
      out_error                => sub_error(15)

    );

  proc: process (kcd_clk) is
    variable accum : unsigned(log2ceil(16+1)-1 downto 0);
  begin
    if rising_edge(kcd_clk) then

      -- Determine how much we need to add to each counter for the strobes
      -- from all the subkernels.
      for counter_idx in 0 to 16-1 loop
        accum := (others => '0');
        for subkernel_idx in 0 to 16-1 loop
          if sub_match(subkernel_idx)(counter_idx) = '1' then
            accum := accum + 1;
          end if;
        end loop;
        increments(counter_idx) <= std_logic_vector(accum);
      end loop;

      accum := (others => '0');
      for subkernel_idx in 0 to 16-1 loop
        if sub_error(subkernel_idx) = '1' then
          accum := accum + 1;
        end if;
      end loop;
      increments(16) <= std_logic_vector(accum);

      -- Add the increment values we determined in the previous cycle to the
      -- counters.
      for counter_idx in 0 to 16 loop
        counters(counter_idx) <= std_logic_vector(
          unsigned(counters(counter_idx))
          + resize(unsigned(increments(counter_idx)), 32)
        );
      end loop;

      -- Reset the counters when the kernel is reset.
      if kcd_reset = '1' or reset = '1' then
        counters <= (others => (others => '0'));
      end if;

      -- Combine the status flags from the subkernels.
      idle <= '1';
      busy <= '0';
      done <= '1';
      for subkernel_idx in 0 to 16-1 loop
        if sub_idle(subkernel_idx) = '0' then
          idle <= '0';
        end if;
        if sub_busy(subkernel_idx) = '1' then
          busy <= '1';
        end if;
        if sub_done(subkernel_idx) = '0' then
          done <= '0';
        end if;
      end loop;
      if kcd_reset = '1' then
        idle <= '0';
        busy <= '1';
        done <= '0';
      end if;

    end if;
  end process;

  count_re_bird                 <= counters(0);
  count_re_bunny                <= counters(1);
  count_re_cat                  <= counters(2);
  count_re_dog                  <= counters(3);
  count_re_ferret               <= counters(4);
  count_re_fish                 <= counters(5);
  count_re_gerbil               <= counters(6);
  count_re_hamster              <= counters(7);
  count_re_horse                <= counters(8);
  count_re_kitten               <= counters(9);
  count_re_lizard               <= counters(10);
  count_re_mouse                <= counters(11);
  count_re_puppy                <= counters(12);
  count_re_rabbit               <= counters(13);
  count_re_rat                  <= counters(14);
  count_re_turtle               <= counters(15);
  count_errors                  <= counters(16);

end architecture;
